# -*- coding: utf-8 -*-
"""
CODE_DICT —— 引擎官方 SoundName 基础代码 -> (中文名, 英文名, side, proto)
数据来源：Westwood 官方音效命名规则 + sounds/ 真实文件 + OpenRA RA2 mod
"""

CODE_DICT = {
    "iena": ("Engineer", "Engineer", "soviet", "infantry"),
    "iein": ("爱因斯坦", "爱因斯坦", "allied", "infantry"),
    "iyup": ("iyup", "iyup", "soviet", "infantry"),
    "ivir": ("ivir", "ivir", "soviet", "infantry"),
    "ifla": ("Flak Trooper", "Flak Trooper", "soviet", "infantry"),
    "ieny": ("ieny", "ieny", "soviet", "infantry"),
    "iggi": ("iggi", "iggi", "soviet", "infantry"),
    "ibru": ("ibru", "ibru", "soviet", "infantry"),
    "itap": ("itap", "itap", "soviet", "infantry"),
    "ibor": ("ibor", "ibor", "soviet", "infantry"),
    "isl2": ("isl2", "isl2", "soviet", "infantry"),
    "ilas": ("ilas", "ilas", "soviet", "infantry"),
    "icia": ("icia", "icia", "soviet", "infantry"),
    "ites": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "iclo": ("iclo", "iclo", "soviet", "infantry"),
    "igi": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "icon": ("Conscript", "Conscript", "soviet", "infantry"),
    "isni": ("Sniper", "Sniper", "soviet", "infantry"),
    "icte": ("Texan", "Texan", "soviet", "infantry"),
    "icis": ("Snow Thin Male", "Snow Thin Male", "soviet", "infantry"),
    "icfa": ("Beach Fat Female", "Beach Fat Female", "soviet", "infantry"),
    "irom": ("irom", "irom", "soviet", "infantry"),
    "agul": ("agul", "agul", "other", "nature"),
    "iini": ("iini", "iini", "soviet", "infantry"),
    "icfs": ("Snow Fat Male", "Snow Fat Male", "soviet", "infantry"),
    "iter": ("Terrorist", "Terrorist", "soviet", "infantry"),
    "vble": ("Black Eagle", "Black Eagle", "allied", "vehicle"),
    "isly": ("isly", "isly", "soviet", "infantry"),
    "ispy": ("Spy", "Spy", "soviet", "infantry"),
    "gradio": ("gradio", "gradio", "other", "structure"),
    "vkir": ("Kirov Airship", "Kirov Airship", "soviet", "vehicle"),
    "icli": ("icli", "icli", "soviet", "infantry"),
    "iens": ("Engineer", "Engineer", "soviet", "infantry"),
    "gfirlo": ("gfirlo", "gfirlo", "other", "structure"),
    "iarn": ("iarn", "iarn", "soviet", "infantry"),
    "awav": ("awav", "awav", "other", "nature"),
    "itan": ("Tanya", "Tanya", "soviet", "infantry"),
    "isea": ("Navy SEAL", "Navy SEAL", "soviet", "infantry"),
    "ichr": ("Chrono Legionnaire", "Chrono Legionnaire", "soviet", "infantry"),
    "vgatlo": ("vgatlo", "vgatlo", "allied", "vehicle"),
    "ides": ("deployed", "deployed", "soviet", "infantry"),
    "iyur": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "isec": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "isl1": ("isl1", "isl1", "soviet", "infantry"),
    "abirj": ("abirj", "abirj", "other", "nature"),
    "vint": ("Harrier", "Harrier", "allied", "vehicle"),
    "iroc": ("shadow", "shadow", "soviet", "infantry"),
    "vblh": ("Night Hawk", "Night Hawk", "allied", "vehicle"),
    "icra": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "vbooa": ("vbooa", "vbooa", "allied", "vehicle"),
    "gexp": ("gexp", "gexp", "other", "structure"),
    "vmas": ("vmas", "vmas", "soviet", "vehicle"),
    "vcho": ("vcho", "vcho", "allied", "vehicle"),
    "vdem": ("Demolition Truck", "Demolition Truck", "soviet", "vehicle"),
    "vmag": ("vmag", "vmag", "soviet", "vehicle"),
    "vsco": ("vsco", "vsco", "soviet", "vehicle"),
    "vchoa": ("vchoa", "vchoa", "allied", "vehicle"),
    "vpri": ("vpri", "vpri", "allied", "vehicle"),
    "aurb": ("aurb", "aurb", "other", "nature"),
    "schrlo": ("schrlo", "schrlo", "other", "support"),
    "vwar": ("vwar", "vwar", "allied", "vehicle"),
    "vwaa": ("Aircraft Carrier", "Aircraft Carrier", "allied", "vehicle"),
    "vifv": ("vifv", "vifv", "allied", "vehicle"),
    "vtan": ("vtan", "vtan", "soviet", "vehicle"),
    "vmir": ("vmir", "vmir", "soviet", "vehicle"),
    "vsla": ("vsla", "vsla", "soviet", "vehicle"),
    "vfla": ("vfla", "vfla", "allied", "vehicle"),
    "vaeg": ("vaeg", "vaeg", "allied", "vehicle"),
    "vgat": ("vgat", "vgat", "allied", "vehicle"),
    "vair": ("vair", "vair", "allied", "vehicle"),
    "vgra": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "vsub": ("vsub", "vsub", "soviet", "vehicle"),
    "vapo": ("vapo", "vapo", "allied", "vehicle"),
    "vbat": ("vbat", "vbat", "allied", "vehicle"),
    "ajur": ("ajur", "ajur", "other", "nature"),
    "abirt": ("abirt", "abirt", "other", "nature"),
    "vv3l": ("vv3l", "vv3l", "soviet", "vehicle"),
    "acri": ("acri", "acri", "other", "nature"),
    "vflo": ("vflo", "vflo", "allied", "vehicle"),
    "vtes": ("vtes", "vtes", "soviet", "vehicle"),
    "vgrs": ("Tesla Tank", "Tesla Tank", "allied", "vehicle"),
    "vwas": ("vwas", "vwas", "allied", "vehicle"),
    "awin": ("awin", "awin", "other", "nature"),
    "vflolo": ("vflolo", "vflolo", "allied", "vehicle"),
    "umovlo": ("umovlo", "umovlo", "other", "ui"),
    "vhoa": ("vhoa", "vhoa", "allied", "vehicle"),
    "vmcy": ("vmcy", "vmcy", "soviet", "vehicle"),
    "vhoy": ("vhoy", "vhoy", "allied", "vehicle"),
    "vboo": ("vboo", "vboo", "allied", "vehicle"),
    "vmig": ("vmig", "vmig", "soviet", "vehicle"),
    "vterlo": ("vterlo", "vterlo", "soviet", "vehicle"),
    "vmca": ("vmca", "vmca", "soviet", "vehicle"),
    "vmcs": ("vmcs", "vmcs", "soviet", "vehicle"),
    "vchr": ("vchr", "vchr", "allied", "vehicle"),
    "vintlo": ("vintlo", "vintlo", "allied", "vehicle"),
    "igiat": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vflaat": ("vflaat", "vflaat", "allied", "vehicle"),
    "aowl": ("aowl", "aowl", "other", "nature"),
    "vblecl": ("vblecl", "vblecl", "allied", "vehicle"),
    "vhos": ("vhos", "vhos", "allied", "vehicle"),
    "atra": ("atra", "atra", "other", "nature"),
    "sgenlo": ("sgenlo", "sgenlo", "other", "support"),
    "vblelo": ("vblelo", "vblelo", "allied", "vehicle"),
    "vlas": ("vlas", "vlas", "soviet", "vehicle"),
    "vcholo": ("vcholo", "vcholo", "allied", "vehicle"),
    "vblhlo": ("vblhlo", "vblhlo", "allied", "vehicle"),
    "abirp": ("abirp", "abirp", "other", "nature"),
    "gdamag": ("gdamag", "gdamag", "other", "structure"),
    "boillo": ("boillo", "boillo", "soviet", "structure"),
    "aprotr": ("aprotr", "aprotr", "other", "nature"),
    "byublo": ("byublo", "byublo", "soviet", "structure"),
    "spsylo": ("spsylo", "spsylo", "other", "support"),
    "vkirlo": ("vkirlo", "vkirlo", "soviet", "vehicle"),
    "iroclo": ("iroclo", "iroclo", "soviet", "infantry"),
    "uscolo": ("uscolo", "uscolo", "other", "ui"),
    "iyuplo": ("iyuplo", "iyuplo", "soviet", "infantry"),
    "vapoat": ("vapoat", "vapoat", "allied", "vehicle"),
    "bgralo": ("bgralo", "bgralo", "soviet", "structure"),
    "sparlo": ("sparlo", "sparlo", "other", "support"),
    "iciv2": ("iciv2", "iciv2", "soviet", "infantry"),
    "vspylo": ("vspylo", "vspylo", "soviet", "vehicle"),
    "xs3c3": ("xs3c3", "xs3c3", "other", "other"),
    "vcoplo": ("vcoplo", "vcoplo", "allied", "vehicle"),
    "xs3c1": ("xs3c1", "xs3c1", "other", "other"),
    "vrobse": ("vrobse", "vrobse", "allied", "vehicle"),
    "iciv1": ("iciv1", "iciv1", "soviet", "infantry"),
    "xs3c2": ("xs3c2", "xs3c2", "other", "other"),
    "acric": ("acric", "acric", "other", "nature"),
    "xs3c4": ("xs3c4", "xs3c4", "other", "other"),
    "islyat": ("islyat", "islyat", "soviet", "infantry"),
    "sirolo": ("sirolo", "sirolo", "other", "support"),
    "idog": ("Attack Dog", "Attack Dog", "soviet", "infantry"),
    "abirm": ("abirm", "abirm", "other", "nature"),
    "swealo": ("swealo", "swealo", "other", "support"),
    "gfoulo": ("gfoulo", "gfoulo", "other", "structure"),
    "ariv": ("ariv", "ariv", "other", "nature"),
    "vifvat": ("vifvat", "vifvat", "allied", "vehicle"),
    "idesat": ("deployed", "deployed", "soviet", "infantry"),
    "grexroa": ("grexroa", "grexroa", "other", "structure"),
    "iyurat": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "btesat": ("btesat", "btesat", "soviet", "structure"),
    "vbooat": ("vbooat", "vbooat", "allied", "vehicle"),
    "vkirbo": ("vkirbo", "vkirbo", "soviet", "vehicle"),
    "iggiat": ("iggiat", "iggiat", "soviet", "infantry"),
    "itesat": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "uslide": ("uslide", "uslide", "other", "ui"),
    "vaccstab": ("vaccstab", "vaccstab", "allied", "vehicle"),
    "vslahab": ("vslahab", "vslahab", "soviet", "vehicle"),
    "iggifef": ("iggifef", "iggifef", "soviet", "infantry"),
    "vbatate": ("vbatate", "vbatate", "allied", "vehicle"),
    "vmagatd": ("vmagatd", "vmagatd", "soviet", "vehicle"),
    "gexpwala": ("gexpwala", "gexpwala", "other", "structure"),
    "vflosta": ("vflosta", "vflosta", "allied", "vehicle"),
    "vdemdiea": ("Demolition Truck", "Demolition Truck", "soviet", "vehicle"),
    "gbeamovc": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vbatsee": ("vbatsee", "vbatsee", "allied", "vehicle"),
    "iinimod": ("iinimod", "iinimod", "soviet", "infantry"),
    "vdemstac": ("vdemstac", "vdemstac", "soviet", "vehicle"),
    "gmumdiec": ("gmumdiec", "gmumdiec", "other", "structure"),
    "vhoysee": ("vhoysee", "vhoysee", "allied", "vehicle"),
    "vlasate": ("vlasate", "vlasate", "soviet", "vehicle"),
    "vmasate": ("vmasate", "vmasate", "soviet", "vehicle"),
    "igimof": ("igimof", "igimof", "soviet", "infantry"),
    "vmassee": ("vmassee", "vmassee", "soviet", "vehicle"),
    "vhordiea": ("vhordiea", "vhordiea", "allied", "vehicle"),
    "iflafed": ("Flak Trooper", "Flak Trooper", "soviet", "infantry"),
    "ieinatd": ("ieinatd", "ieinatd", "soviet", "infantry"),
    "gcamsela": ("gcamsela", "gcamsela", "other", "structure"),
    "icloatd": ("icloatd", "icloatd", "soviet", "infantry"),
    "gexpapob": ("gexpapob", "gexpapob", "other", "structure"),
    "ifladie": ("Flak Trooper", "Flak Trooper", "soviet", "infantry"),
    "ienapow": ("Engineer", "Engineer", "soviet", "infantry"),
    "isl1fed": ("isl1fed", "isl1fed", "soviet", "infantry"),
    "vboomoe": ("vboomoe", "vboomoe", "allied", "vehicle"),
    "vpristaa": ("vpristaa", "vpristaa", "allied", "vehicle"),
    "bspyof": ("bspyof", "bspyof", "soviet", "structure"),
    "ibrucrd": ("ibrucrd", "ibrucrd", "soviet", "infantry"),
    "ivirmod": ("ivirmod", "ivirmod", "soviet", "infantry"),
    "ivirmoe": ("ivirmoe", "ivirmoe", "soviet", "infantry"),
    "vmasstaa": ("vmasstaa", "vmasstaa", "soviet", "vehicle"),
    "icfsmod": ("Snow Fat Male", "Snow Fat Male", "soviet", "infantry"),
    "vrhiattd": ("vrhiattd", "vrhiattd", "allied", "vehicle"),
    "gcopdiea": ("gcopdiea", "gcopdiea", "other", "structure"),
    "gchimova": ("Monkey", "Monkey", "other", "structure"),
    "iclired": ("iclired", "iclired", "soviet", "infantry"),
    "vboomod": ("vboomod", "vboomod", "allied", "vehicle"),
    "isl1fee": ("isl1fee", "isl1fee", "soviet", "infantry"),
    "gbromova": ("gbromova", "gbromova", "other", "structure"),
    "gexpapoc": ("gexpapoc", "gexpapoc", "other", "structure"),
    "icloate": ("icloate", "icloate", "soviet", "infantry"),
    "ieinate": ("ieinate", "ieinate", "soviet", "infantry"),
    "iclosee": ("iclosee", "iclosee", "soviet", "infantry"),
    "vfloatta": ("vfloatta", "vfloatta", "allied", "vehicle"),
    "ieinsee": ("ieinsee", "ieinsee", "soviet", "infantry"),
    "grexmovb": ("grexmovb", "grexmovb", "other", "structure"),
    "vmasatd": ("vmasatd", "vmasatd", "soviet", "vehicle"),
    "vlasatd": ("vlasatd", "vlasatd", "soviet", "vehicle"),
    "iboraib": ("iboraib", "iboraib", "soviet", "infantry"),
    "gmumdieb": ("gmumdieb", "gmumdieb", "other", "structure"),
    "vchaselb": ("vchaselb", "vchaselb", "allied", "vehicle"),
    "vbatstaa": ("vbatstaa", "vbatstaa", "allied", "vehicle"),
    "idesatf": ("deployed", "deployed", "soviet", "infantry"),
    "ugarris": ("ugarris", "ugarris", "other", "ui"),
    "iinimoe": ("iinimoe", "iinimoe", "soviet", "infantry"),
    "vdemstab": ("vdemstab", "vdemstab", "soviet", "vehicle"),
    "vmagsee": ("vmagsee", "vmagsee", "soviet", "vehicle"),
    "vhoasee": ("vhoasee", "vhoasee", "allied", "vehicle"),
    "gbeamovb": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vbatatd": ("vbatatd", "vbatatd", "allied", "vehicle"),
    "gcowmovb": ("Cow", "Cow", "other", "structure"),
    "vmagate": ("vmagate", "vmagate", "soviet", "vehicle"),
    "ucamera": ("ucamera", "ucamera", "other", "ui"),
    "vslahac": ("vslahac", "vslahac", "soviet", "vehicle"),
    "vmcamof": ("vmcamof", "vmcamof", "soviet", "vehicle"),
    "vlasatta": ("vlasatta", "vlasatta", "soviet", "vehicle"),
    "vmcamod": ("vmcamod", "vmcamod", "soviet", "vehicle"),
    "vaccstaa": ("vaccstaa", "vaccstaa", "allied", "vehicle"),
    "vslahaa": ("vslahaa", "vslahaa", "soviet", "vehicle"),
    "iggifee": ("iggifee", "iggifee", "soviet", "infantry"),
    "ichrkill": ("ichrkill", "ichrkill", "soviet", "infantry"),
    "ienymod": ("ienymod", "ienymod", "soviet", "infantry"),
    "gexpwalb": ("gexpwalb", "gexpwalb", "other", "structure"),
    "vflostb": ("vflostb", "vflostb", "allied", "vehicle"),
    "vbatsef": ("vbatsef", "vbatsef", "allied", "vehicle"),
    "vmcymoe": ("vmcymoe", "vmcymoe", "soviet", "vehicle"),
    "vintdna": ("vintdna", "vintdna", "allied", "vehicle"),
    "idesatd": ("deployed", "deployed", "soviet", "infantry"),
    "vpriatd": ("vpriatd", "vpriatd", "allied", "vehicle"),
    "vbatstac": ("vbatstac", "vbatstac", "allied", "vehicle"),
    "urepair": ("urepair", "urepair", "other", "ui"),
    "vmasatf": ("vmasatf", "vmasatf", "soviet", "vehicle"),
    "vlasatf": ("vlasatf", "vlasatf", "soviet", "vehicle"),
    "siroon": ("siroon", "siroon", "other", "support"),
    "vmassef": ("vmassef", "vmassef", "soviet", "vehicle"),
    "vhordieb": ("vhordieb", "vhordieb", "allied", "vehicle"),
    "igimoe": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vlassef": ("vlassef", "vlassef", "soviet", "vehicle"),
    "gexpapoa": ("gexpapoa", "gexpapoa", "other", "structure"),
    "gcamselb": ("gcamselb", "gcamselb", "other", "structure"),
    "idogsela": ("Attack Dog", "Attack Dog", "soviet", "infantry"),
    "gbromovc": ("gbromovc", "gbromovc", "other", "structure"),
    "vscomoe": ("vscomoe", "vscomoe", "soviet", "vehicle"),
    "vpristab": ("vpristab", "vpristab", "allied", "vehicle"),
    "vmasstac": ("vmasstac", "vmasstac", "soviet", "vehicle"),
    "vmasstab": ("vmasstab", "vmasstab", "soviet", "vehicle"),
    "vpristac": ("vpristac", "vpristac", "allied", "vehicle"),
    "vscomod": ("vscomod", "vscomod", "soviet", "vehicle"),
    "gchimovb": ("Monkey", "Monkey", "other", "structure"),
    "gbromovb": ("gbromovb", "gbromovb", "other", "structure"),
    "vrobon": ("vrobon", "vrobon", "allied", "vehicle"),
    "gcamselc": ("gcamselc", "gcamselc", "other", "structure"),
    "vlasseg": ("vlasseg", "vlasseg", "soviet", "vehicle"),
    "igimod": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vcabstaa": ("vcabstaa", "vcabstaa", "allied", "vehicle"),
    "grexmova": ("grexmova", "grexmova", "other", "structure"),
    "gtimesh": ("gtimesh", "gtimesh", "other", "structure"),
    "vlasatg": ("vlasatg", "vlasatg", "soviet", "vehicle"),
    "vchasela": ("vchasela", "vchasela", "allied", "vehicle"),
    "gmumdiea": ("gmumdiea", "gmumdiea", "other", "structure"),
    "iggidie": ("iggidie", "iggidie", "soviet", "infantry"),
    "vbatstab": ("vbatstab", "vbatstab", "allied", "vehicle"),
    "vpriate": ("vpriate", "vpriate", "allied", "vehicle"),
    "idesate": ("deployed", "deployed", "soviet", "infantry"),
    "vdemstaa": ("vdemstaa", "vdemstaa", "soviet", "vehicle"),
    "idessee": ("deployed", "deployed", "soviet", "infantry"),
    "vprisee": ("vprisee", "vprisee", "allied", "vehicle"),
    "vmcymod": ("vmcymod", "vmcymod", "soviet", "vehicle"),
    "gbeamova": ("Polar Bear", "Polar Bear", "other", "structure"),
    "ienymoe": ("ienymoe", "ienymoe", "soviet", "infantry"),
    "gexpwalc": ("gexpwalc", "gexpwalc", "other", "structure"),
    "vmagatf": ("vmagatf", "vmagatf", "soviet", "vehicle"),
    "iggifed": ("iggifed", "iggifed", "soviet", "infantry"),
    "gcowmova": ("Cow", "Cow", "other", "structure"),
    "bpilattd": ("bpilattd", "bpilattd", "soviet", "structure"),
    "vmcamoe": ("vmcamoe", "vmcamoe", "soviet", "vehicle"),
    "vmcasef": ("vmcasef", "vmcasef", "soviet", "vehicle"),
    "vtermova": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "vcrusha": ("vcrusha", "vcrusha", "allied", "vehicle"),
    "vmagstac": ("vmagstac", "vmagstac", "soviet", "vehicle"),
    "vifvstab": ("vifvstab", "vifvstab", "allied", "vehicle"),
    "galldiea": ("galldiea", "galldiea", "other", "structure"),
    "vslahad": ("vslahad", "vslahad", "soviet", "vehicle"),
    "gbroamba": ("gbroamba", "gbroamba", "other", "structure"),
    "vmagmoe": ("vmagmoe", "vmagmoe", "soviet", "vehicle"),
    "vhoamoe": ("vhoamoe", "vhoamoe", "allied", "vehicle"),
    "gchiamba": ("gchiamba", "gchiamba", "other", "structure"),
    "vbatmod": ("vbatmod", "vbatmod", "allied", "vehicle"),
    "iggideb": ("iggideb", "iggideb", "soviet", "infantry"),
    "iinisee": ("iinisee", "iinisee", "soviet", "infantry"),
    "vblesee": ("vblesee", "vblesee", "allied", "vehicle"),
    "iiniate": ("iiniate", "iiniate", "soviet", "infantry"),
    "iarnrec": ("iarnrec", "iarnrec", "soviet", "infantry"),
    "vhoymod": ("vhoymod", "vhoymod", "allied", "vehicle"),
    "ceva0": ("ceva0", "ceva0", "other", "other"),
    "bbioenta": ("bbioenta", "bbioenta", "soviet", "structure"),
    "vblhattb": ("vblhattb", "vblhattb", "allied", "vehicle"),
    "vdoldiea": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "ieinmoe": ("ieinmoe", "ieinmoe", "soviet", "infantry"),
    "iclomoe": ("iclomoe", "iclomoe", "soviet", "infantry"),
    "iiniatta": ("iiniatta", "iiniatta", "soviet", "infantry"),
    "vlasmod": ("vlasmod", "vlasmod", "soviet", "vehicle"),
    "vslade": ("vslade", "vslade", "soviet", "vehicle"),
    "vmasmod": ("vmasmod", "vmasmod", "soviet", "vehicle"),
    "islydie": ("islydie", "islydie", "soviet", "infantry"),
    "vdesattb": ("vdesattb", "vdesattb", "soviet", "vehicle"),
    "icfsatd": ("Snow Fat Male", "Snow Fat Male", "soviet", "infantry"),
    "ubase": ("ubase", "ubase", "other", "ui"),
    "islyfed": ("islyfed", "islyfed", "soviet", "infantry"),
    "vtadstab": ("vtadstab", "vtadstab", "soviet", "vehicle"),
    "ivirsee": ("ivirsee", "ivirsee", "soviet", "infantry"),
    "vrhiattc": ("vrhiattc", "vrhiattc", "allied", "vehicle"),
    "ibrucrb": ("ibrucrb", "ibrucrb", "soviet", "infantry"),
    "ibrucrc": ("ibrucrc", "ibrucrc", "soviet", "infantry"),
    "vrhiattb": ("vrhiattb", "vrhiattb", "allied", "vehicle"),
    "icfssee": ("Snow Fat Male", "Snow Fat Male", "soviet", "infantry"),
    "icondie": ("Conscript", "Conscript", "soviet", "infantry"),
    "iviratd": ("iviratd", "iviratd", "soviet", "infantry"),
    "islyfee": ("islyfee", "islyfee", "soviet", "infantry"),
    "vboosee": ("vboosee", "vboosee", "allied", "vehicle"),
    "iclireb": ("iclireb", "iclireb", "soviet", "infantry"),
    "varmattb": ("varmattb", "varmattb", "allied", "vehicle"),
    "vmasmoe": ("vmasmoe", "vmasmoe", "soviet", "vehicle"),
    "igisef": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "iclomod": ("iclomod", "iclomod", "soviet", "infantry"),
    "ieinmod": ("ieinmod", "ieinmod", "soviet", "infantry"),
    "vrobatta": ("vrobatta", "vrobatta", "allied", "vehicle"),
    "igiatf": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "gsancrub": ("gsancrub", "gsancrub", "other", "structure"),
    "iarnreb": ("iarnreb", "iarnreb", "soviet", "infantry"),
    "vhoymoe": ("vhoymoe", "vhoymoe", "allied", "vehicle"),
    "gmumdied": ("gmumdied", "gmumdied", "other", "structure"),
    "iiniatd": ("iiniatd", "iiniatd", "soviet", "infantry"),
    "iggidec": ("iggidec", "iggidec", "soviet", "infantry"),
    "vflostf": ("vflostf", "vflostf", "allied", "vehicle"),
    "vmagmod": ("vmagmod", "vmagmod", "soviet", "vehicle"),
    "vbatmoe": ("vbatmoe", "vbatmoe", "allied", "vehicle"),
    "vhoamod": ("vhoamod", "vhoamod", "allied", "vehicle"),
    "gexpwamb": ("gexpwamb", "gexpwamb", "other", "structure"),
    "gship": ("gship", "gship", "other", "structure"),
    "bpilatta": ("bpilatta", "bpilatta", "soviet", "structure"),
    "vslahae": ("vslahae", "vslahae", "soviet", "vehicle"),
    "ugamclos": ("ugamclos", "ugamclos", "other", "ui"),
    "vmagstab": ("vmagstab", "vmagstab", "soviet", "vehicle"),
    "isl1atta": ("isl1atta", "isl1atta", "soviet", "infantry"),
    "vifvstac": ("vifvstac", "vifvstac", "allied", "vehicle"),
    "vifvstaa": ("vifvstaa", "vifvstaa", "allied", "vehicle"),
    "vdematd": ("Demolition Truck", "Demolition Truck", "soviet", "vehicle"),
    "vmcasee": ("vmcasee", "vmcasee", "soviet", "vehicle"),
    "ienyate": ("ienyate", "ienyate", "soviet", "infantry"),
    "bpilattc": ("bpilattc", "bpilattc", "soviet", "structure"),
    "ienysee": ("ienysee", "ienysee", "soviet", "infantry"),
    "gbroambb": ("gbroambb", "gbroambb", "other", "structure"),
    "gchiambb": ("gchiambb", "gchiambb", "other", "structure"),
    "vflostd": ("vflostd", "vflostd", "allied", "vehicle"),
    "vprimoe": ("vprimoe", "vprimoe", "allied", "vehicle"),
    "idesmoe": ("deployed", "deployed", "soviet", "infantry"),
    "iggidea": ("iggidea", "iggidea", "soviet", "infantry"),
    "iiniatf": ("iiniatf", "iiniatf", "soviet", "infantry"),
    "vblesef": ("Black Eagle", "Black Eagle", "allied", "vehicle"),
    "vdoldieb": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "igiatd": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vblhatta": ("vblhatta", "vblhatta", "allied", "vehicle"),
    "ichratd": ("Chrono Legionnaire", "Chrono Legionnaire", "soviet", "infantry"),
    "vdesatta": ("vdesatta", "vdesatta", "soviet", "vehicle"),
    "vifvtran": ("vifvtran", "vifvtran", "allied", "vehicle"),
    "iviratf": ("iviratf", "iviratf", "soviet", "infantry"),
    "vtadstaa": ("vtadstaa", "vtadstaa", "soviet", "vehicle"),
    "ibrucra": ("ibrucra", "ibrucra", "soviet", "infantry"),
    "vscoatd": ("vscoatd", "vscoatd", "soviet", "vehicle"),
    "vscoate": ("vscoate", "vscoate", "soviet", "vehicle"),
    "vrhiatta": ("vrhiatta", "vrhiatta", "allied", "vehicle"),
    "iteschaa": ("iteschaa", "iteschaa", "soviet", "infantry"),
    "vsladepa": ("vsladepa", "vsladepa", "soviet", "vehicle"),
    "vscosee": ("vscosee", "vscosee", "soviet", "vehicle"),
    "iviratg": ("iviratg", "iviratg", "soviet", "infantry"),
    "varmatta": ("varmatta", "varmatta", "allied", "vehicle"),
    "iclirea": ("iclirea", "iclirea", "soviet", "infantry"),
    "vlasmof": ("vlasmof", "vlasmof", "soviet", "vehicle"),
    "igisee": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "ichrsee": ("Chrono Legionnaire", "Chrono Legionnaire", "soviet", "infantry"),
    "igiate": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "gsancrua": ("gsancrua", "gsancrua", "other", "structure"),
    "iarnrea": ("iarnrea", "iarnrea", "soviet", "infantry"),
    "idesmod": ("deployed", "deployed", "soviet", "infantry"),
    "vprimod": ("vprimod", "vprimod", "allied", "vehicle"),
    "vmcysee": ("vmcysee", "vmcysee", "soviet", "vehicle"),
    "gexpwama": ("gexpwama", "gexpwama", "other", "structure"),
    "gchiambc": ("gchiambc", "gchiambc", "other", "structure"),
    "vfloste": ("vfloste", "vfloste", "allied", "vehicle"),
    "bpilattb": ("bpilattb", "bpilattb", "soviet", "structure"),
    "ienyatd": ("ienyatd", "ienyatd", "soviet", "infantry"),
    "vmagstaa": ("vmagstaa", "vmagstaa", "soviet", "vehicle"),
    "vdemate": ("Demolition Truck", "Demolition Truck", "soviet", "vehicle"),
    "vmcsmod": ("vmcsmod", "vmcsmod", "soviet", "vehicle"),
    "vmcvstaa": ("vmcvstaa", "vmcvstaa", "soviet", "vehicle"),
    "ades": ("ades", "ades", "other", "nature"),
    "vtersela": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "baocattc": ("baocattc", "baocattc", "soviet", "structure"),
    "icraatd": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "snuksire": ("snuksire", "snuksire", "other", "support"),
    "gbigben": ("gbigben", "gbigben", "other", "structure"),
    "gcarsela": ("gcarsela", "gcarsela", "other", "structure"),
    "vseastad": ("vseastad", "vseastad", "soviet", "vehicle"),
    "gmumattc": ("gmumattc", "gmumattc", "other", "structure"),
    "vmirat": ("vmirat", "vmirat", "soviet", "vehicle"),
    "ibrusee": ("ibrusee", "ibrusee", "soviet", "infantry"),
    "vsquat": ("Giant Squid", "Giant Squid", "soviet", "vehicle"),
    "ibruate": ("ibruate", "ibruate", "soviet", "infantry"),
    "gcrafree": ("gcrafree", "gcrafree", "other", "structure"),
    "ts6": ("ts6", "ts6", "other", "other"),
    "vboostaa": ("vboostaa", "vboostaa", "allied", "vehicle"),
    "isl2see": ("isl2see", "isl2see", "soviet", "infantry"),
    "isl2ate": ("isl2ate", "isl2ate", "soviet", "infantry"),
    "vv3latd": ("vv3latd", "vv3latd", "soviet", "vehicle"),
    "vv3late": ("vv3late", "vv3late", "soviet", "vehicle"),
    "isl2atd": ("isl2atd", "isl2atd", "soviet", "infantry"),
    "isl1haa": ("isl1haa", "isl1haa", "soviet", "infantry"),
    "vchrtele": ("vchrtele", "vchrtele", "allied", "vehicle"),
    "vv3lsee": ("vv3lsee", "vv3lsee", "soviet", "vehicle"),
    "ibordie": ("ibordie", "ibordie", "soviet", "infantry"),
    "gvirexpa": ("gvirexpa", "gvirexpa", "other", "structure"),
    "btandowa": ("btandowa", "btandowa", "soviet", "structure"),
    "ts7": ("ts7", "ts7", "other", "other"),
    "iborfed": ("iborfed", "iborfed", "soviet", "infantry"),
    "ibruatd": ("ibruatd", "ibruatd", "soviet", "infantry"),
    "vflodiea": ("vflodiea", "vflodiea", "allied", "vehicle"),
    "ucheer": ("ucheer", "ucheer", "other", "ui"),
    "gmumattb": ("gmumattb", "gmumattb", "other", "structure"),
    "vlasstaa": ("vlasstaa", "vlasstaa", "soviet", "vehicle"),
    "gexpwasa": ("gexpwasa", "gexpwasa", "other", "structure"),
    "gblacrub": ("gblacrub", "gblacrub", "other", "structure"),
    "vchamovd": ("vchamovd", "vchamovd", "allied", "vehicle"),
    "vaegath": ("vaegath", "vaegath", "allied", "vehicle"),
    "vchrsee": ("vchrsee", "vchrsee", "allied", "vehicle"),
    "baocattb": ("baocattb", "baocattb", "soviet", "structure"),
    "icrasee": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "vmcsmoe": ("vmcsmoe", "vmcsmoe", "soviet", "vehicle"),
    "bpriat": ("bpriat", "bpriat", "soviet", "structure"),
    "ilasmod": ("ilasmod", "ilasmod", "soviet", "infantry"),
    "iclisee": ("iclisee", "iclisee", "soviet", "infantry"),
    "icraseg": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "vterselb": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "icliate": ("icliate", "icliate", "soviet", "infantry"),
    "schropen": ("schropen", "schropen", "other", "support"),
    "bpatatta": ("bpatatta", "bpatatta", "soviet", "structure"),
    "vlasstac": ("vlasstac", "vlasstac", "soviet", "vehicle"),
    "vwarmod": ("vwarmod", "vwarmod", "allied", "vehicle"),
    "iarnate": ("iarnate", "iarnate", "soviet", "infantry"),
    "vrhistad": ("vrhistad", "vrhistad", "allied", "vehicle"),
    "vosplana": ("vosplana", "vosplana", "soviet", "vehicle"),
    "vboostab": ("vboostab", "vboostab", "allied", "vehicle"),
    "ts5": ("ts5", "ts5", "other", "other"),
    "ienspow": ("Engineer", "Engineer", "soviet", "infantry"),
    "ts10": ("ts10", "ts10", "other", "other"),
    "vnavupa": ("vnavupa", "vnavupa", "soviet", "vehicle"),
    "isl1hac": ("isl1hac", "isl1hac", "soviet", "infantry"),
    "icfamod": ("Beach Fat Female", "Beach Fat Female", "soviet", "infantry"),
    "isl1hab": ("isl1hab", "isl1hab", "soviet", "infantry"),
    "snukintr": ("snukintr", "snukintr", "other", "support"),
    "ts4": ("ts4", "ts4", "other", "other"),
    "gvirexpb": ("gvirexpb", "gvirexpb", "other", "structure"),
    "uwarning": ("uwarning", "uwarning", "other", "ui"),
    "vpriatta": ("vpriatta", "vpriatta", "allied", "vehicle"),
    "iarnatd": ("iarnatd", "iarnatd", "soviet", "infantry"),
    "vchodie": ("vchodie", "vchodie", "allied", "vehicle"),
    "vwarmoe": ("vwarmoe", "vwarmoe", "allied", "vehicle"),
    "gmumatta": ("gmumatta", "gmumatta", "other", "structure"),
    "vlasstab": ("vlasstab", "vlasstab", "soviet", "vehicle"),
    "gairraid": ("gairraid", "gairraid", "other", "structure"),
    "gexpwasb": ("gexpwasb", "gexpwasb", "other", "structure"),
    "gblacrua": ("gblacrua", "gblacrua", "other", "structure"),
    "baocatta": ("baocatta", "baocatta", "soviet", "structure"),
    "icliatd": ("icliatd", "icliatd", "soviet", "infantry"),
    "vhossee": ("vhossee", "vhossee", "allied", "vehicle"),
    "icrasef": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "ilasmoe": ("ilasmoe", "ilasmoe", "soviet", "infantry"),
    "gpowon": ("gpowon", "gpowon", "other", "structure"),
    "vmcssee": ("vmcssee", "vmcssee", "soviet", "vehicle"),
    "vchrmoe": ("vchrmoe", "vchrmoe", "allied", "vehicle"),
    "gcowselc": ("Cow", "Cow", "other", "structure"),
    "vchamovc": ("vchamovc", "vchamovc", "allied", "vehicle"),
    "vseastab": ("vseastab", "vseastab", "soviet", "vehicle"),
    "vmagatta": ("vmagatta", "vmagatta", "soviet", "vehicle"),
    "vrhistaa": ("vrhistaa", "vrhistaa", "allied", "vehicle"),
    "ibrumod": ("ibrumod", "ibrumod", "soviet", "infantry"),
    "vdolatta": ("vdolatta", "vdolatta", "soviet", "vehicle"),
    "gcammova": ("gcammova", "gcammova", "other", "structure"),
    "gpsyampb": ("gpsyampb", "gpsyampb", "other", "structure"),
    "bmetdamb": ("bmetdamb", "bmetdamb", "soviet", "structure"),
    "grexselc": ("grexselc", "grexselc", "other", "structure"),
    "vv3lmoe": ("vv3lmoe", "vv3lmoe", "soviet", "vehicle"),
    "isl2mod": ("isl2mod", "isl2mod", "soviet", "infantry"),
    "vrobstab": ("vrobstab", "vrobstab", "allied", "vehicle"),
    "vrobstac": ("vrobstac", "vrobstac", "allied", "vehicle"),
    "gchisela": ("Monkey", "Monkey", "other", "structure"),
    "gbrosela": ("gbrosela", "gbrosela", "other", "structure"),
    "itapdie": ("itapdie", "itapdie", "soviet", "infantry"),
    "bpripow": ("bpripow", "bpripow", "soviet", "structure"),
    "isl2moe": ("isl2moe", "isl2moe", "soviet", "infantry"),
    "vv3lmod": ("vv3lmod", "vv3lmod", "soviet", "vehicle"),
    "vdesstaa": ("vdesstaa", "vdesstaa", "soviet", "vehicle"),
    "grexselb": ("grexselb", "grexselb", "other", "structure"),
    "vhortakb": ("vhortakb", "vhortakb", "allied", "vehicle"),
    "ts1": ("ts1", "ts1", "other", "other"),
    "bmetdamc": ("bmetdamc", "bmetdamc", "soviet", "structure"),
    "gpsyampc": ("gpsyampc", "gpsyampc", "other", "structure"),
    "vtadatta": ("vtadatta", "vtadatta", "soviet", "vehicle"),
    "gflare": ("gflare", "gflare", "other", "structure"),
    "itapfed": ("itapfed", "itapfed", "soviet", "infantry"),
    "ibrumoe": ("ibrumoe", "ibrumoe", "soviet", "infantry"),
    "vrobdiea": ("vrobdiea", "vrobdiea", "allied", "vehicle"),
    "vifvatta": ("vifvatta", "vifvatta", "allied", "vehicle"),
    "vseastac": ("vseastac", "vseastac", "soviet", "vehicle"),
    "vchamovb": ("vchamovb", "vchamovb", "allied", "vehicle"),
    "sgenon": ("sgenon", "sgenon", "other", "support"),
    "igidepb": ("igidepb", "igidepb", "soviet", "infantry"),
    "gcowselb": ("Cow", "Cow", "other", "structure"),
    "vchrmod": ("vchrmod", "vchrmod", "allied", "vehicle"),
    "icramod": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "gbeaselb": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vlanstaa": ("vlanstaa", "vlanstaa", "soviet", "vehicle"),
    "icivattb": ("icivattb", "icivattb", "soviet", "infantry"),
    "ilassee": ("ilassee", "ilassee", "soviet", "infantry"),
    "sparadra": ("sparadra", "sparadra", "other", "support"),
    "itesatta": ("itesatta", "itesatta", "soviet", "infantry"),
    "spsyreve": ("spsyreve", "spsyreve", "other", "support"),
    "iclimod": ("iclimod", "iclimod", "soviet", "infantry"),
    "vlanstac": ("vlanstac", "vlanstac", "soviet", "vehicle"),
    "icramof": ("Crazy Ivan", "Crazy Ivan", "soviet", "infantry"),
    "vhosmoe": ("vhosmoe", "vhosmoe", "allied", "vehicle"),
    "ilasate": ("ilasate", "ilasate", "soviet", "infantry"),
    "igensqua": ("igensqua", "igensqua", "soviet", "infantry"),
    "sforceon": ("sforceon", "sforceon", "other", "support"),
    "gupgrad": ("gupgrad", "gupgrad", "other", "structure"),
    "vseastaa": ("vseastaa", "vseastaa", "soviet", "vehicle"),
    "vwarsee": ("vwarsee", "vwarsee", "allied", "vehicle"),
    "vblhdiea": ("vblhdiea", "vblhdiea", "allied", "vehicle"),
    "vrhistab": ("vrhistab", "vrhistab", "allied", "vehicle"),
    "vtadattc": ("vtadattc", "vtadattc", "soviet", "vehicle"),
    "gpsyampa": ("gpsyampa", "gpsyampa", "other", "structure"),
    "gcammovb": ("gcammovb", "gcammovb", "other", "structure"),
    "vchaatca": ("vchaatca", "vchaatca", "allied", "vehicle"),
    "vwarate": ("vwarate", "vwarate", "allied", "vehicle"),
    "ts3": ("ts3", "ts3", "other", "other"),
    "iromfee": ("iromfee", "iromfee", "soviet", "infantry"),
    "iteratd": ("Terrorist", "Terrorist", "soviet", "infantry"),
    "bmetdama": ("bmetdama", "bmetdama", "soviet", "structure"),
    "iarnmod": ("iarnmod", "iarnmod", "soviet", "infantry"),
    "gexit": ("gexit", "gexit", "other", "structure"),
    "vsqudiea": ("Giant Squid", "Giant Squid", "soviet", "vehicle"),
    "snukread": ("snukread", "snukread", "other", "support"),
    "uradarof": ("uradarof", "uradarof", "other", "ui"),
    "icfaatd": ("Beach Fat Female", "Beach Fat Female", "soviet", "infantry"),
    "gbroselc": ("gbroselc", "gbroselc", "other", "structure"),
    "idogmova": ("Attack Dog", "Attack Dog", "soviet", "infantry"),
    "isl1hae": ("isl1hae", "isl1hae", "soviet", "infantry"),
    "vrobstaa": ("vrobstaa", "vrobstaa", "allied", "vehicle"),
    "vfloat": ("vfloat", "vfloat", "allied", "vehicle"),
    "gchiselb": ("Monkey", "Monkey", "other", "structure"),
    "isl1had": ("isl1had", "isl1had", "soviet", "infantry"),
    "gbroselb": ("gbroselb", "gbroselb", "other", "structure"),
    "iromdie": ("iromdie", "iromdie", "soviet", "infantry"),
    "vdesstab": ("vdesstab", "vdesstab", "soviet", "vehicle"),
    "grexsela": ("grexsela", "grexsela", "other", "structure"),
    "vhortaka": ("vhortaka", "vhortaka", "allied", "vehicle"),
    "iromfed": ("iromfed", "iromfed", "soviet", "infantry"),
    "iarnmoe": ("iarnmoe", "iarnmoe", "soviet", "infantry"),
    "vwaratd": ("vwaratd", "vwaratd", "allied", "vehicle"),
    "ts2": ("ts2", "ts2", "other", "other"),
    "vtadattb": ("vtadattb", "vtadattb", "soviet", "vehicle"),
    "vrhistac": ("vrhistac", "vrhistac", "allied", "vehicle"),
    "igenexpa": ("igenexpa", "igenexpa", "soviet", "infantry"),
    "uplanadd": ("uplanadd", "uplanadd", "other", "ui"),
    "vchamova": ("vchamova", "vchamova", "allied", "vehicle"),
    "igidepa": ("igidepa", "igidepa", "soviet", "infantry"),
    "gcowsela": ("Cow", "Cow", "other", "structure"),
    "utext": ("utext", "utext", "other", "ui"),
    "ichrmova": ("ichrmova", "ichrmova", "soviet", "infantry"),
    "idogatca": ("Attack Dog", "Attack Dog", "soviet", "infantry"),
    "ilasatd": ("ilasatd", "ilasatd", "soviet", "infantry"),
    "vhosmod": ("vhosmod", "vhosmod", "allied", "vehicle"),
    "vlanstab": ("vlanstab", "vlanstab", "soviet", "vehicle"),
    "iclimoe": ("iclimoe", "iclimoe", "soviet", "infantry"),
    "vchodiea": ("vchodiea", "vchodiea", "allied", "vehicle"),
    "gbeasela": ("Polar Bear", "Polar Bear", "other", "structure"),
    "icivatta": ("icivatta", "icivatta", "soviet", "infantry"),
    "itanatta": ("itanatta", "itanatta", "soviet", "infantry"),
    "bpowdiea": ("bpowdiea", "bpowdiea", "soviet", "structure"),
    "vrobsela": ("vrobsela", "vrobsela", "allied", "vehicle"),
    "bpsydiea": ("bpsydiea", "bpsydiea", "soviet", "structure"),
    "vorehara": ("vorehara", "vorehara", "soviet", "vehicle"),
    "icteatd": ("Texan", "Texan", "soviet", "infantry"),
    "iborattb": ("iborattb", "iborattb", "soviet", "infantry"),
    "vflomoe": ("vflomoe", "vflomoe", "allied", "vehicle"),
    "vifvmof": ("vifvmof", "vifvmof", "allied", "vehicle"),
    "gbrodiea": ("gbrodiea", "gbrodiea", "other", "structure"),
    "vmirstac": ("vmirstac", "vmirstac", "soviet", "vehicle"),
    "gchidiea": ("Monkey", "Monkey", "other", "structure"),
    "vtesstaa": ("vtesstaa", "vtesstaa", "soviet", "vehicle"),
    "vchrgoa": ("vchrgoa", "vchrgoa", "allied", "vehicle"),
    "vgendiec": ("vgendiec", "vgendiec", "allied", "vehicle"),
    "gbeadieb": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vgristaa": ("vgristaa", "vgristaa", "allied", "vehicle"),
    "vsubatta": ("vsubatta", "vsubatta", "soviet", "vehicle"),
    "vtanmod": ("vtanmod", "vtanmod", "soviet", "vehicle"),
    "gcrafire": ("gcrafire", "gcrafire", "other", "structure"),
    "ucreddn": ("ucreddn", "ucreddn", "other", "ui"),
    "ubeacon": ("ubeacon", "ubeacon", "other", "ui"),
    "ibruatta": ("ibruatta", "ibruatta", "soviet", "infantry"),
    "uqeue": ("uqeue", "uqeue", "other", "ui"),
    "itapsee": ("itapsee", "itapsee", "soviet", "infantry"),
    "vospdiea": ("vospdiea", "vospdiea", "soviet", "vehicle"),
    "iseaatta": ("iseaatta", "iseaatta", "soviet", "infantry"),
    "vmirmof": ("vmirmof", "vmirmof", "soviet", "vehicle"),
    "irocmod": ("shadow", "shadow", "soviet", "infantry"),
    "iyupcrd": ("iyupcrd", "iyupcrd", "soviet", "infantry"),
    "ibormod": ("ibormod", "ibormod", "soviet", "infantry"),
    "irocmoe": ("shadow", "shadow", "soviet", "infantry"),
    "ibormoe": ("ibormoe", "ibormoe", "soviet", "infantry"),
    "itapatd": ("itapatd", "itapatd", "soviet", "infantry"),
    "vmirmog": ("vmirmog", "vmirmog", "soviet", "vehicle"),
    "sweastrd": ("sweastrd", "sweastrd", "other", "support"),
    "galiattb": ("Alligator", "Alligator", "other", "structure"),
    "vaircraa": ("vaircraa", "vaircraa", "allied", "vehicle"),
    "gdefuse": ("gdefuse", "gdefuse", "other", "structure"),
    "vgendieb": ("vgendieb", "vgendieb", "allied", "vehicle"),
    "vmirstab": ("vmirstab", "vmirstab", "soviet", "vehicle"),
    "vintmod": ("Harrier", "Harrier", "allied", "vehicle"),
    "vslamof": ("vslamof", "vslamof", "soviet", "vehicle"),
    "vflomod": ("vflomod", "vflomod", "allied", "vehicle"),
    "igenmela": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "gbrostab": ("gbrostab", "gbrostab", "other", "structure"),
    "vchodepa": ("vchodepa", "vchodepa", "allied", "vehicle"),
    "bpowdieb": ("bpowdieb", "bpowdieb", "soviet", "structure"),
    "itanattb": ("itanattb", "itanattb", "soviet", "infantry"),
    "vwaamoe": ("Aircraft Carrier", "Aircraft Carrier", "allied", "vehicle"),
    "genter": ("genter", "genter", "other", "structure"),
    "vaegmod": ("vaegmod", "vaegmod", "allied", "vehicle"),
    "igenmelc": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "grexdiea": ("grexdiea", "grexdiea", "other", "structure"),
    "islyred": ("islyred", "islyred", "soviet", "infantry"),
    "iboratta": ("iboratta", "iboratta", "soviet", "infantry"),
    "vifvmoe": ("vifvmoe", "vifvmoe", "allied", "vehicle"),
    "vslamod": ("vslamod", "vslamod", "soviet", "vehicle"),
    "gchidieb": ("Monkey", "Monkey", "other", "structure"),
    "vflaatd": ("vflaatd", "vflaatd", "allied", "vehicle"),
    "vtesstab": ("vtesstab", "vtesstab", "soviet", "vehicle"),
    "vgristab": ("vgristab", "vgristab", "allied", "vehicle"),
    "vtesate": ("vtesate", "vtesate", "soviet", "vehicle"),
    "gbeadiea": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vchrgob": ("vchrgob", "vchrgob", "allied", "vehicle"),
    "vchomod": ("vchomod", "vchomod", "allied", "vehicle"),
    "gcowdiea": ("Cow", "Cow", "other", "structure"),
    "vtessee": ("vtessee", "vtessee", "soviet", "vehicle"),
    "ubonus": ("ubonus", "ubonus", "other", "ui"),
    "ibruattb": ("ibruattb", "ibruattb", "soviet", "infantry"),
    "vaircrac": ("vaircrac", "vaircrac", "allied", "vehicle"),
    "sgenopen": ("sgenopen", "sgenopen", "other", "support"),
    "iromate": ("iromate", "iromate", "soviet", "infantry"),
    "gmummova": ("gmummova", "gmummova", "other", "structure"),
    "iseaattb": ("iseaattb", "iseaattb", "soviet", "infantry"),
    "vmirmoe": ("vmirmoe", "vmirmoe", "soviet", "vehicle"),
    "swearead": ("swearead", "swearead", "other", "support"),
    "gmindcle": ("gmindcle", "gmindcle", "other", "structure"),
    "iromsee": ("iromsee", "iromsee", "soviet", "infantry"),
    "irocmof": ("shadow", "shadow", "soviet", "infantry"),
    "vmirmod": ("vmirmod", "vmirmod", "soviet", "vehicle"),
    "iromatd": ("iromatd", "iromatd", "soviet", "infantry"),
    "bgraatta": ("bgraatta", "bgraatta", "soviet", "structure"),
    "vaircrab": ("vaircrab", "vaircrab", "allied", "vehicle"),
    "icraloop": ("icraloop", "icraloop", "soviet", "infantry"),
    "galiatta": ("Alligator", "Alligator", "other", "structure"),
    "ibruattc": ("ibruattc", "ibruattc", "soviet", "infantry"),
    "uselbuil": ("uselbuil", "uselbuil", "other", "ui"),
    "vchomoe": ("vchomoe", "vchomoe", "allied", "vehicle"),
    "vospstaa": ("vospstaa", "vospstaa", "soviet", "vehicle"),
    "vgendiea": ("vgendiea", "vgendiea", "allied", "vehicle"),
    "vtesatd": ("vtesatd", "vtesatd", "soviet", "vehicle"),
    "vchrgoc": ("vchrgoc", "vchrgoc", "allied", "vehicle"),
    "vgristac": ("vgristac", "vgristac", "allied", "vehicle"),
    "vflaate": ("vflaate", "vflaate", "allied", "vehicle"),
    "vmirstaa": ("vmirstaa", "vmirstaa", "soviet", "vehicle"),
    "vslamoe": ("vslamoe", "vslamoe", "soviet", "vehicle"),
    "vifvmod": ("vifvmod", "vifvmod", "allied", "vehicle"),
    "vflasee": ("vflasee", "vflasee", "allied", "vehicle"),
    "iyupred": ("iyupred", "iyupred", "soviet", "infantry"),
    "ilasfed": ("ilasfed", "ilasfed", "soviet", "infantry"),
    "islyree": ("islyree", "islyree", "soviet", "infantry"),
    "byubatta": ("byubatta", "byubatta", "soviet", "structure"),
    "vsqusela": ("Giant Squid", "Giant Squid", "soviet", "vehicle"),
    "goreupa": ("goreupa", "goreupa", "other", "structure"),
    "ilasdie": ("ilasdie", "ilasdie", "soviet", "infantry"),
    "vblhmod": ("Night Hawk", "Night Hawk", "allied", "vehicle"),
    "igenmelb": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vaegmoe": ("vaegmoe", "vaegmoe", "allied", "vehicle"),
    "gbrostaa": ("gbrostaa", "gbrostaa", "other", "structure"),
    "vwaamod": ("Aircraft Carrier", "Aircraft Carrier", "allied", "vehicle"),
    "vapostab": ("vapostab", "vapostab", "allied", "vehicle"),
    "gmondiea": ("gmondiea", "gmondiea", "other", "structure"),
    "vaegatf": ("vaegatf", "vaegatf", "allied", "vehicle"),
    "vintatd": ("Harrier", "Harrier", "allied", "vehicle"),
    "islyrea": ("islyrea", "islyrea", "soviet", "infantry"),
    "vslasef": ("vslasef", "vslasef", "soviet", "vehicle"),
    "vfloatd": ("vfloatd", "vfloatd", "allied", "vehicle"),
    "vdrestaa": ("vdrestaa", "vdrestaa", "soviet", "vehicle"),
    "isl2fee": ("isl2fee", "isl2fee", "soviet", "infantry"),
    "vgendiee": ("vgendiee", "vgendiee", "allied", "vehicle"),
    "vtanate": ("vtanate", "vtanate", "soviet", "vehicle"),
    "vtansee": ("vtansee", "vtansee", "soviet", "vehicle"),
    "ts9": ("ts9", "ts9", "other", "other"),
    "gmummovd": ("gmummovd", "gmummovd", "other", "structure"),
    "sweastrc": ("sweastrc", "sweastrc", "other", "support"),
    "ibrufee": ("ibrufee", "ibrufee", "soviet", "infantry"),
    "iborate": ("iborate", "iborate", "soviet", "infantry"),
    "itapmod": ("itapmod", "itapmod", "soviet", "infantry"),
    "irocate": ("shadow", "shadow", "soviet", "infantry"),
    "vdolatca": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "irocsee": ("shadow", "shadow", "soviet", "infantry"),
    "iborsee": ("iborsee", "iborsee", "soviet", "infantry"),
    "isl2die": ("isl2die", "isl2die", "soviet", "infantry"),
    "vmirsef": ("vmirsef", "vmirsef", "soviet", "vehicle"),
    "ibruattf": ("ibruattf", "ibruattf", "soviet", "infantry"),
    "iboratd": ("iboratd", "iboratd", "soviet", "infantry"),
    "ibrufed": ("ibrufed", "ibrufed", "soviet", "infantry"),
    "irocatd": ("shadow", "shadow", "soviet", "infantry"),
    "snukexpl": ("snukexpl", "snukexpl", "other", "support"),
    "sweastrb": ("sweastrb", "sweastrb", "other", "support"),
    "vaegstab": ("vaegstab", "vaegstab", "allied", "vehicle"),
    "gnavsina": ("gnavsina", "gnavsina", "other", "structure"),
    "gallmova": ("gallmova", "gallmova", "other", "structure"),
    "ts8": ("ts8", "ts8", "other", "other"),
    "ibrudie": ("ibrudie", "ibrudie", "soviet", "infantry"),
    "vkirdiea": ("vkirdiea", "vkirdiea", "soviet", "vehicle"),
    "vterdiea": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "vtanatd": ("vtanatd", "vtanatd", "soviet", "vehicle"),
    "vblediea": ("Black Eagle", "Black Eagle", "allied", "vehicle"),
    "vgendied": ("vgendied", "vgendied", "allied", "vehicle"),
    "isl2fed": ("isl2fed", "isl2fed", "soviet", "infantry"),
    "vfloate": ("vfloate", "vfloate", "allied", "vehicle"),
    "ictemod": ("Texan", "Texan", "soviet", "infantry"),
    "vslaseg": ("vslaseg", "vslaseg", "soviet", "vehicle"),
    "vifvsef": ("vifvsef", "vifvsef", "allied", "vehicle"),
    "vintate": ("Harrier", "Harrier", "allied", "vehicle"),
    "iroccraa": ("iroccraa", "iroccraa", "soviet", "infantry"),
    "iyuprea": ("iyuprea", "iyuprea", "soviet", "infantry"),
    "vv3latta": ("vv3latta", "vv3latta", "soviet", "vehicle"),
    "igenzapa": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "vaegatg": ("vaegatg", "vaegatg", "allied", "vehicle"),
    "vdolmova": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "vapostac": ("vapostac", "vapostac", "allied", "vehicle"),
    "gpowof": ("gpowof", "gpowof", "other", "structure"),
    "vintatta": ("vintatta", "vintatta", "allied", "vehicle"),
    "vblhatd": ("Night Hawk", "Night Hawk", "allied", "vehicle"),
    "vaegsee": ("vaegsee", "vaegsee", "allied", "vehicle"),
    "siroread": ("siroread", "siroread", "other", "support"),
    "irocatta": ("irocatta", "irocatta", "soviet", "infantry"),
    "vapostaa": ("vapostaa", "vapostaa", "allied", "vehicle"),
    "vaegate": ("vaegate", "vaegate", "allied", "vehicle"),
    "vslaate": ("vslaate", "vslaate", "soviet", "vehicle"),
    "vifvatd": ("vifvatd", "vifvatd", "allied", "vehicle"),
    "iyuprec": ("iyuprec", "iyuprec", "soviet", "infantry"),
    "islyreb": ("islyreb", "islyreb", "soviet", "infantry"),
    "vflamoe": ("vflamoe", "vflamoe", "allied", "vehicle"),
    "vslasee": ("vslasee", "vslasee", "soviet", "vehicle"),
    "vgendief": ("vgendief", "vgendief", "allied", "vehicle"),
    "vchrgod": ("vchrgod", "vchrgod", "allied", "vehicle"),
    "vdrestab": ("vdrestab", "vdrestab", "soviet", "vehicle"),
    "ichratta": ("ichratta", "ichratta", "soviet", "infantry"),
    "vchosee": ("vchosee", "vchosee", "allied", "vehicle"),
    "vtesmod": ("vtesmod", "vtesmod", "soviet", "vehicle"),
    "vmiratd": ("vmiratd", "vmiratd", "soviet", "vehicle"),
    "ibruattd": ("ibruattd", "ibruattd", "soviet", "infantry"),
    "isniatta": ("isniatta", "isniatta", "soviet", "infantry"),
    "vgrsatd": ("Tesla Tank", "Tesla Tank", "allied", "vehicle"),
    "vdolatcb": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "vchaatta": ("vchaatta", "vchaatta", "allied", "vehicle"),
    "irommod": ("irommod", "irommod", "soviet", "infantry"),
    "irocsef": ("shadow", "shadow", "soviet", "infantry"),
    "iarnfee": ("iarnfee", "iarnfee", "soviet", "infantry"),
    "irommoe": ("irommoe", "irommoe", "soviet", "infantry"),
    "iarnfed": ("iarnfed", "iarnfed", "soviet", "infantry"),
    "irocseg": ("shadow", "shadow", "soviet", "infantry"),
    "ilasatta": ("ilasatta", "ilasatta", "soviet", "infantry"),
    "vdolatcc": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "sweaintr": ("sweaintr", "sweaintr", "other", "support"),
    "vmirsee": ("vmirsee", "vmirsee", "soviet", "vehicle"),
    "ibruatte": ("ibruatte", "ibruatte", "soviet", "infantry"),
    "schrmov": ("schrmov", "schrmov", "other", "support"),
    "vmirate": ("vmirate", "vmirate", "soviet", "vehicle"),
    "uradaron": ("uradaron", "uradaron", "other", "ui"),
    "vaegstaa": ("vaegstaa", "vaegstaa", "allied", "vehicle"),
    "sweastra": ("sweastra", "sweastra", "other", "support"),
    "vintupa": ("vintupa", "vintupa", "allied", "vehicle"),
    "gallmovb": ("gallmovb", "gallmovb", "other", "structure"),
    "vtesmoe": ("vtesmoe", "vtesmoe", "soviet", "vehicle"),
    "vterdieb": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "umessage": ("umessage", "umessage", "other", "ui"),
    "iarndie": ("iarndie", "iarndie", "soviet", "infantry"),
    "vbledieb": ("Black Eagle", "Black Eagle", "allied", "vehicle"),
    "vdrestac": ("vdrestac", "vdrestac", "soviet", "vehicle"),
    "vchrgoe": ("vchrgoe", "vchrgoe", "allied", "vehicle"),
    "vifvsee": ("vifvsee", "vifvsee", "allied", "vehicle"),
    "vchoat": ("vchoat", "vchoat", "allied", "vehicle"),
    "islyrec": ("islyrec", "islyrec", "soviet", "infantry"),
    "vflamod": ("vflamod", "vflamod", "allied", "vehicle"),
    "iyupreb": ("iyupreb", "iyupreb", "soviet", "infantry"),
    "vifvate": ("vifvate", "vifvate", "allied", "vehicle"),
    "idogatta": ("idogatta", "idogatta", "soviet", "infantry"),
    "iroccrab": ("iroccrab", "iroccrab", "soviet", "infantry"),
    "iclifed": ("iclifed", "iclifed", "soviet", "infantry"),
    "vaegatd": ("vaegatd", "vaegatd", "allied", "vehicle"),
    "vv3lattb": ("vv3lattb", "vv3lattb", "soviet", "vehicle"),
    "sforceof": ("sforceof", "sforceof", "other", "support"),
    "umenucl": ("umenucl", "umenucl", "other", "ui"),
    "vdolmovb": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "iclidie": ("iclidie", "iclidie", "soviet", "infantry"),
    "iviratta": ("iviratta", "iviratta", "soviet", "infantry"),
    "vmiratta": ("vmiratta", "vmiratta", "soviet", "vehicle"),
    "vflastac": ("vflastac", "vflastac", "allied", "vehicle"),
    "iinifee": ("iinifee", "iinifee", "soviet", "infantry"),
    "itesmod": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "grexfooa": ("grexfooa", "grexfooa", "other", "structure"),
    "gbeafeaa": ("Polar Bear", "Polar Bear", "other", "structure"),
    "grexattb": ("grexattb", "grexattb", "other", "structure"),
    "bsenattd": ("bsenattd", "bsenattd", "soviet", "structure"),
    "vairatd": ("vairatd", "vairatd", "allied", "vehicle"),
    "bgendiee": ("bgendiee", "bgendiee", "soviet", "structure"),
    "sirodefb": ("sirodefb", "sirodefb", "other", "support"),
    "vgatatf": ("vgatatf", "vgatatf", "allied", "vehicle"),
    "gchiatta": ("gchiatta", "gchiatta", "other", "structure"),
    "iborcrb": ("iborcrb", "iborcrb", "soviet", "infantry"),
    "isecmod": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "iyupsee": ("iyupsee", "iyupsee", "soviet", "infantry"),
    "gbeaattb": ("Polar Bear", "Polar Bear", "other", "structure"),
    "isl1moe": ("isl1moe", "isl1moe", "soviet", "infantry"),
    "islyatd": ("islyatd", "islyatd", "soviet", "infantry"),
    "ivirfee": ("ivirfee", "ivirfee", "soviet", "infantry"),
    "vslastab": ("vslastab", "vslastab", "soviet", "vehicle"),
    "iyupate": ("iyupate", "iyupate", "soviet", "infantry"),
    "itapcrd": ("itapcrd", "itapcrd", "soviet", "infantry"),
    "vmigatta": ("vmigatta", "vmigatta", "soviet", "vehicle"),
    "iseaexa": ("Navy SEAL", "Navy SEAL", "soviet", "infantry"),
    "gchifeab": ("Monkey", "Monkey", "other", "structure"),
    "vospatta": ("vospatta", "vospatta", "soviet", "vehicle"),
    "iarnatta": ("iarnatta", "iarnatta", "soviet", "infantry"),
    "vgramoe": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "vgriattc": ("vgriattc", "vgriattc", "allied", "vehicle"),
    "vhorlanb": ("vhorlanb", "vhorlanb", "allied", "vehicle"),
    "vwarhab": ("vwarhab", "vwarhab", "allied", "vehicle"),
    "iconatta": ("iconatta", "iconatta", "soviet", "infantry"),
    "iflamod": ("Flak Trooper", "Flak Trooper", "soviet", "infantry"),
    "bspyon": ("bspyon", "bspyon", "soviet", "structure"),
    "vtesattb": ("vtesattb", "vtesattb", "soviet", "vehicle"),
    "vwarhac": ("vwarhac", "vwarhac", "allied", "vehicle"),
    "vgriattb": ("vgriattb", "vgriattb", "allied", "vehicle"),
    "gcraspee": ("gcraspee", "gcraspee", "other", "structure"),
    "vgramod": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "iconatd": ("Conscript", "Conscript", "soviet", "infantry"),
    "ivirdie": ("ivirdie", "ivirdie", "soviet", "infantry"),
    "umenscol": ("umenscol", "umenscol", "other", "ui"),
    "iyupatd": ("iyupatd", "iyupatd", "soviet", "infantry"),
    "gexpifva": ("gexpifva", "gexpifva", "other", "structure"),
    "ivirfed": ("ivirfed", "ivirfed", "soviet", "infantry"),
    "islyate": ("islyate", "islyate", "soviet", "infantry"),
    "gallsela": ("gallsela", "gallsela", "other", "structure"),
    "isl1mod": ("isl1mod", "isl1mod", "soviet", "infantry"),
    "iborcrc": ("iborcrc", "iborcrc", "soviet", "infantry"),
    "iinidie": ("iinidie", "iinidie", "soviet", "infantry"),
    "sirodefc": ("sirodefc", "sirodefc", "other", "support"),
    "vairate": ("vairate", "vairate", "allied", "vehicle"),
    "bgendied": ("bgendied", "bgendied", "soviet", "structure"),
    "vbledie": ("Black Eagle", "Black Eagle", "allied", "vehicle"),
    "vairsee": ("vairsee", "vairsee", "allied", "vehicle"),
    "grexattc": ("grexattc", "grexattc", "other", "structure"),
    "iinifed": ("iinifed", "iinifed", "soviet", "infantry"),
    "bclov": ("bclov", "bclov", "soviet", "structure"),
    "itesmoe": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "vwasmod": ("vwasmod", "vwasmod", "allied", "vehicle"),
    "vapoatf": ("vapoatf", "vapoatf", "allied", "vehicle"),
    "vflastab": ("vflastab", "vflastab", "allied", "vehicle"),
    "vdolsela": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "vapoatd": ("vapoatd", "vapoatd", "allied", "vehicle"),
    "grexfoob": ("grexfoob", "grexfoob", "other", "structure"),
    "itansee": ("Tanya", "Tanya", "soviet", "infantry"),
    "itapree": ("itapree", "itapree", "soviet", "infantry"),
    "gbeafeab": ("Polar Bear", "Polar Bear", "other", "structure"),
    "grexfala": ("grexfala", "grexfala", "other", "structure"),
    "grexatta": ("grexatta", "grexatta", "other", "structure"),
    "iggimod": ("iggimod", "iggimod", "soviet", "infantry"),
    "vchrhae": ("vchrhae", "vchrhae", "allied", "vehicle"),
    "iyurmod": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "vgatsee": ("vgatsee", "vgatsee", "allied", "vehicle"),
    "sirodefa": ("sirodefa", "sirodefa", "other", "support"),
    "bgendief": ("bgendief", "bgendief", "soviet", "structure"),
    "gexpshaa": ("gexpshaa", "gexpshaa", "other", "structure"),
    "gchiattb": ("gchiattb", "gchiattb", "other", "structure"),
    "vgatate": ("vgatate", "vgatate", "allied", "vehicle"),
    "ienyfee": ("ienyfee", "ienyfee", "soviet", "infantry"),
    "vkiratd": ("Kirov Airship", "Kirov Airship", "soviet", "vehicle"),
    "iborcra": ("iborcra", "iborcra", "soviet", "infantry"),
    "bflaattd": ("bflaattd", "bflaattd", "soviet", "structure"),
    "ispyatd": ("Spy", "Spy", "soviet", "infantry"),
    "igidie": ("Pentagon General", "Pentagon General", "soviet", "infantry"),
    "iyupsef": ("iyupsef", "iyupsef", "soviet", "infantry"),
    "gbeaatta": ("Polar Bear", "Polar Bear", "other", "structure"),
    "vslastaa": ("vslastaa", "vslastaa", "soviet", "vehicle"),
    "gexpifvc": ("gexpifvc", "gexpifvc", "other", "structure"),
    "gcraheal": ("gcraheal", "gcraheal", "other", "structure"),
    "borerefa": ("borerefa", "borerefa", "soviet", "structure"),
    "iyupatf": ("iyupatf", "iyupatf", "soviet", "infantry"),
    "gchifeaa": ("Monkey", "Monkey", "other", "structure"),
    "vsubmod": ("vsubmod", "vsubmod", "soviet", "vehicle"),
    "iseaexb": ("Navy SEAL", "Navy SEAL", "soviet", "infantry"),
    "iarnattb": ("iarnattb", "iarnattb", "soviet", "infantry"),
    "vgramof": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "ucredup": ("ucredup", "ucredup", "other", "ui"),
    "vwarhaa": ("vwarhaa", "vwarhaa", "allied", "vehicle"),
    "vhorlana": ("vhorlana", "vhorlana", "allied", "vehicle"),
    "iconattb": ("iconattb", "iconattb", "soviet", "infantry"),
    "uplan": ("uplan", "uplan", "other", "ui"),
    "vtesatta": ("vtesatta", "vtesatta", "soviet", "vehicle"),
    "iconattc": ("iconattc", "iconattc", "soviet", "infantry"),
    "bpsydet": ("bpsydet", "bpsydet", "soviet", "structure"),
    "vgriatta": ("vgriatta", "vgriatta", "allied", "vehicle"),
    "iseaexc": ("iseaexc", "iseaexc", "soviet", "infantry"),
    "vsubmoe": ("vsubmoe", "vsubmoe", "soviet", "vehicle"),
    "vroboff": ("vroboff", "vroboff", "allied", "vehicle"),
    "siroof": ("siroof", "siroof", "other", "support"),
    "iyupatg": ("iyupatg", "iyupatg", "soviet", "infantry"),
    "gexpifvb": ("gexpifvb", "gexpifvb", "other", "structure"),
    "gallselb": ("gallselb", "gallselb", "other", "structure"),
    "gcraarmo": ("gcraarmo", "gcraarmo", "other", "structure"),
    "ienyfed": ("ienyfed", "ienyfed", "soviet", "infantry"),
    "gchiattc": ("gchiattc", "gchiattc", "other", "structure"),
    "vgatatd": ("vgatatd", "vgatatd", "allied", "vehicle"),
    "vchrhad": ("vchrhad", "vchrhad", "allied", "vehicle"),
    "iggimoe": ("iggimoe", "iggimoe", "soviet", "infantry"),
    "itanatd": ("Tanya", "Tanya", "soviet", "infantry"),
    "vaposee": ("vaposee", "vaposee", "allied", "vehicle"),
    "ienydie": ("ienydie", "ienydie", "soviet", "infantry"),
    "grexfooc": ("grexfooc", "grexfooc", "other", "structure"),
    "itesmof": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "itapred": ("itapred", "itapred", "soviet", "infantry"),
    "spsydom": ("spsydom", "spsydom", "other", "support"),
    "vdolselb": ("Dolphin", "Dolphin", "soviet", "vehicle"),
    "vapoate": ("vapoate", "vapoate", "allied", "vehicle"),
    "vflastaa": ("vflastaa", "vflastaa", "allied", "vehicle"),
    "vmagat": ("vmagat", "vmagat", "soviet", "vehicle"),
    "gexpcraa": ("gexpcraa", "gexpcraa", "other", "structure"),
    "itessee": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "vrobmova": ("vrobmova", "vrobmova", "allied", "vehicle"),
    "btespow": ("btespow", "btespow", "soviet", "structure"),
    "vifvrepa": ("vifvrepa", "vifvrepa", "allied", "vehicle"),
    "itesate": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "vairmoe": ("vairmoe", "vairmoe", "allied", "vehicle"),
    "vv3lstab": ("vv3lstab", "vv3lstab", "soviet", "vehicle"),
    "iggisef": ("iggisef", "iggisef", "soviet", "infantry"),
    "gcamstab": ("gcamstab", "gcamstab", "other", "structure"),
    "gtugboaa": ("gtugboaa", "gtugboaa", "other", "structure"),
    "bsenattb": ("bsenattb", "bsenattb", "soviet", "structure"),
    "sirodefd": ("sirodefd", "sirodefd", "other", "support"),
    "gexpbara": ("gexpbara", "gexpbara", "other", "structure"),
    "bgendiec": ("bgendiec", "bgendiec", "soviet", "structure"),
    "gtimeshi": ("gtimeshi", "gtimeshi", "other", "structure"),
    "vwarattb": ("vwarattb", "vwarattb", "allied", "vehicle"),
    "islymoe": ("islymoe", "islymoe", "soviet", "infantry"),
    "iborcrd": ("iborcrd", "iborcrd", "soviet", "infantry"),
    "isecsee": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "iyupmod": ("iyupmod", "iyupmod", "soviet", "infantry"),
    "bflaatta": ("bflaatta", "bflaatta", "soviet", "structure"),
    "ieindie": ("ieindie", "ieindie", "soviet", "infantry"),
    "itapcrb": ("itapcrb", "itapcrb", "soviet", "infantry"),
    "iclodie": ("iclodie", "iclodie", "soviet", "infantry"),
    "isecate": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "isl1atd": ("isl1atd", "isl1atd", "soviet", "infantry"),
    "vaegatta": ("vaegatta", "vaegatta", "allied", "vehicle"),
    "ieinfed": ("ieinfed", "ieinfed", "soviet", "infantry"),
    "iclofed": ("iclofed", "iclofed", "soviet", "infantry"),
    "iflaatd": ("Flak Trooper", "Flak Trooper", "soviet", "infantry"),
    "uplace": ("uplace", "uplace", "other", "ui"),
    "iconmod": ("Conscript", "Conscript", "soviet", "infantry"),
    "isnimoe": ("Sniper", "Sniper", "soviet", "infantry"),
    "vwarhad": ("vwarhad", "vwarhad", "allied", "vehicle"),
    "vgraatd": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "gmumselb": ("gmumselb", "gmumselb", "other", "structure"),
    "vgraate": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "gmumselc": ("gmumselc", "gmumselc", "other", "structure"),
    "vdreattb": ("vdreattb", "vdreattb", "soviet", "vehicle"),
    "isnimod": ("Sniper", "Sniper", "soviet", "infantry"),
    "vrobatca": ("vrobatca", "vrobatca", "allied", "vehicle"),
    "vgrasee": ("Mirage Tank", "Mirage Tank", "allied", "vehicle"),
    "iclofee": ("iclofee", "iclofee", "soviet", "infantry"),
    "bgrinda": ("bgrinda", "bgrinda", "soviet", "structure"),
    "ieinfee": ("ieinfee", "ieinfee", "soviet", "infantry"),
    "uacbopen": ("uacbopen", "uacbopen", "other", "ui"),
    "isl1ate": ("isl1ate", "isl1ate", "soviet", "infantry"),
    "isecatd": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "spsyopen": ("spsyopen", "spsyopen", "other", "support"),
    "icliatta": ("icliatta", "icliatta", "soviet", "infantry"),
    "itapcrc": ("itapcrc", "itapcrc", "soviet", "infantry"),
    "vkiratta": ("vkiratta", "vkiratta", "soviet", "vehicle"),
    "awatloa": ("awatloa", "awatloa", "other", "nature"),
    "vteratta": ("Terror Drone", "Terror Drone", "soviet", "vehicle"),
    "isl1see": ("isl1see", "isl1see", "soviet", "infantry"),
    "iborcre": ("iborcre", "iborcre", "soviet", "infantry"),
    "iyupmoe": ("iyupmoe", "iyupmoe", "soviet", "infantry"),
    "vgatstaa": ("vgatstaa", "vgatstaa", "allied", "vehicle"),
    "vbleatta": ("vbleatta", "vbleatta", "allied", "vehicle"),
    "vchastaa": ("vchastaa", "vchastaa", "allied", "vehicle"),
    "islymod": ("islymod", "islymod", "soviet", "infantry"),
    "bgendieb": ("bgendieb", "bgendieb", "soviet", "structure"),
    "vsqumovb": ("Giant Squid", "Giant Squid", "soviet", "vehicle"),
    "vchrhaa": ("vchrhaa", "vchrhaa", "allied", "vehicle"),
    "vtroselb": ("vtroselb", "vtroselb", "soviet", "vehicle"),
    "bsenattc": ("bsenattc", "bsenattc", "soviet", "structure"),
    "vv3lstac": ("vv3lstac", "vv3lstac", "soviet", "vehicle"),
    "vairmod": ("vairmod", "vairmod", "allied", "vehicle"),
    "ucommand": ("ucommand", "ucommand", "other", "ui"),
    "itesatd": ("Tesla Trooper", "Tesla Trooper", "soviet", "infantry"),
    "gcamdiea": ("gcamdiea", "gcamdiea", "other", "structure"),
    "iggidepa": ("iggidepa", "iggidepa", "soviet", "infantry"),
    "itanmof": ("Tanya", "Tanya", "soviet", "infantry"),
    "vflastad": ("vflastad", "vflastad", "allied", "vehicle"),
    "itaprea": ("itaprea", "itaprea", "soviet", "infantry"),
    "vintdiea": ("vintdiea", "vintdiea", "allied", "vehicle"),
    "itaprec": ("itaprec", "itaprec", "soviet", "infantry"),
    "itanmod": ("Tanya", "Tanya", "soviet", "infantry"),
    "vapomoe": ("vapomoe", "vapomoe", "allied", "vehicle"),
    "irocdiea": ("shadow", "shadow", "soviet", "infantry"),
    "vrobmovb": ("vrobmovb", "vrobmovb", "allied", "vehicle"),
    "gtugboab": ("gtugboab", "gtugboab", "other", "structure"),
    "bsenatta": ("bsenatta", "bsenatta", "soviet", "structure"),
    "iggisee": ("iggisee", "iggisee", "soviet", "infantry"),
    "iyursee": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "gcamstaa": ("gcamstaa", "gcamstaa", "other", "structure"),
    "vv3lstaa": ("vv3lstaa", "vv3lstaa", "soviet", "vehicle"),
    "vgatmod": ("vgatmod", "vgatmod", "allied", "vehicle"),
    "vspysnap": ("vspysnap", "vspysnap", "soviet", "vehicle"),
    "vchrhac": ("vchrhac", "vchrhac", "allied", "vehicle"),
    "iyurate": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "iggiate": ("iggiate", "iggiate", "soviet", "infantry"),
    "gexpbarb": ("gexpbarb", "gexpbarb", "other", "structure"),
    "vgatstac": ("vgatstac", "vgatstac", "allied", "vehicle"),
    "vchastac": ("vchastac", "vchastac", "allied", "vehicle"),
    "vwaratta": ("vwaratta", "vwaratta", "allied", "vehicle"),
    "bflaattb": ("bflaattb", "bflaattb", "soviet", "structure"),
    "isecsef": ("Secret Service", "Secret Service", "soviet", "infantry"),
    "iyupmog": ("iyupmog", "iyupmog", "soviet", "infantry"),
    "itapcra": ("itapcra", "itapcra", "soviet", "infantry"),
    "awatloc": ("awatloc", "awatloc", "other", "nature"),
    "vaegattb": ("vaegattb", "vaegattb", "allied", "vehicle"),
    "ispymoe": ("Spy", "Spy", "soviet", "infantry"),
    "icliattc": ("icliattc", "icliattc", "soviet", "infantry"),
    "icraatta": ("icraatta", "icraatta", "soviet", "infantry"),
    "vkircraa": ("vkircraa", "vkircraa", "soviet", "vehicle"),
    "vsubsee": ("vsubsee", "vsubsee", "soviet", "vehicle"),
    "gcraprom": ("gcraprom", "gcraprom", "other", "structure"),
    "unewgame": ("unewgame", "unewgame", "other", "ui"),
    "vsubate": ("vsubate", "vsubate", "soviet", "vehicle"),
    "iconattd": ("iconattd", "iconattd", "soviet", "infantry"),
    "gmumsela": ("gmumsela", "gmumsela", "other", "structure"),
    "vchadiea": ("vchadiea", "vchadiea", "allied", "vehicle"),
    "vdreatta": ("vdreatta", "vdreatta", "soviet", "vehicle"),
    "iconatte": ("iconatte", "iconatte", "soviet", "infantry"),
    "snuklaun": ("snuklaun", "snuklaun", "other", "support"),
    "vsubatd": ("vsubatd", "vsubatd", "soviet", "vehicle"),
    "icliattb": ("icliattb", "icliattb", "soviet", "infantry"),
    "ispymod": ("Spy", "Spy", "soviet", "infantry"),
    "awatlob": ("awatlob", "awatlob", "other", "nature"),
    "iyupmof": ("iyupmof", "iyupmof", "soviet", "infantry"),
    "isl1sef": ("isl1sef", "isl1sef", "soviet", "infantry"),
    "bflaattc": ("bflaattc", "bflaattc", "soviet", "structure"),
    "vchastab": ("vchastab", "vchastab", "allied", "vehicle"),
    "vbleattb": ("vbleattb", "vbleattb", "allied", "vehicle"),
    "vgatstab": ("vgatstab", "vgatstab", "allied", "vehicle"),
    "gexpbarc": ("gexpbarc", "gexpbarc", "other", "structure"),
    "bgendiea": ("bgendiea", "bgendiea", "soviet", "structure"),
    "vsqumova": ("Giant Squid", "Giant Squid", "soviet", "vehicle"),
    "iggiatd": ("iggiatd", "iggiatd", "soviet", "infantry"),
    "iyuratd": ("Psi Commando", "Psi Commando", "soviet", "infantry"),
    "utab": ("utab", "utab", "other", "ui"),
    "bparatta": ("bparatta", "bparatta", "soviet", "structure"),
    "vtrosela": ("vtrosela", "vtrosela", "soviet", "vehicle"),
    "vchrhab": ("vchrhab", "vchrhab", "allied", "vehicle"),
    "vgatmoe": ("vgatmoe", "vgatmoe", "allied", "vehicle"),
    "idogdiea": ("Attack Dog", "Attack Dog", "soviet", "infantry"),
    "isl1lia": ("isl1lia", "isl1lia", "soviet", "infantry"),
    "btanupa": ("btanupa", "btanupa", "soviet", "structure"),
    "vapomod": ("vapomod", "vapomod", "allied", "vehicle"),
    "itanmoe": ("Tanya", "Tanya", "soviet", "infantry"),
    "vintdieb": ("vintdieb", "vintdieb", "allied", "vehicle"),
    "itapreb": ("itapreb", "itapreb", "soviet", "infantry"),
}
# 总计 1092 个基础代码

import re

# --------------------------------------------------------------------------
# 动作 / 状态后缀 -> 中文说明
# --------------------------------------------------------------------------
ACTION_INFO = {
    "at":   ("攻击",   "接到攻击指令后，向目标开火时发出的音效。"),
    "ata":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效。"),
    "atb":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "atc":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "atd":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "ate":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "atf":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "atg":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "ath":  ("攻击",   "接到攻击指令后，向目标开火时发出的音效（变体）。"),
    "att":  ("攻击",   "持续开火 / 连射时发出的音效。"),
    "attb": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "attc": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "attd": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "atte": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "attf": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "atth": ("攻击",   "持续开火 / 连射时发出的音效（变体）。"),
    "atca": ("攻击",   "特殊攻击 / 充能攻击触发的音效。"),
    "at2a": ("攻击",   "攻击动作第二套变体的音效。"),
    "mo":   ("移动",   "接到移动指令、单位行进时发出的音效。"),
    "moa":  ("移动",   "接到移动指令、单位行进时发出的音效。"),
    "mob":  ("移动",   "接到移动指令、单位行进时发出的音效（变体）。"),
    "moc":  ("移动",   "接到移动指令、单位行进时发出的音效（变体）。"),
    "mod":  ("移动",   "接到移动指令、单位行进时发出的音效（变体）。"),
    "moe":  ("移动",   "接到移动指令、单位行进时发出的音效（变体）。"),
    "mof":  ("移动",   "接到移动指令、单位行进时发出的音效（变体）。"),
    "mov":  ("移动",   "行进循环 / 持续移动时发出的环境音。"),
    "mova": ("移动",   "行进循环 / 持续移动时发出的环境音（变体）。"),
    "movb": ("移动",   "行进循环 / 持续移动时发出的环境音（变体）。"),
    "movc": ("移动",   "行进循环 / 持续移动时发出的环境音（变体）。"),
    "movd": ("移动",   "行进循环 / 持续移动时发出的环境音（变体）。"),
    "se":   ("选中",   "指挥官点选该单位时的应答语音。"),
    "sea":  ("选中",   "指挥官点选该单位时的应答语音。"),
    "seb":  ("选中",   "指挥官点选该单位时的应答语音（变体）。"),
    "sec":  ("选中",   "指挥官点选该单位时的应答语音（变体）。"),
    "sed":  ("选中",   "指挥官点选该单位时的应答语音（变体）。"),
    "see":  ("选中",   "指挥官点选该单位时的应答语音（变体）。"),
    "sef":  ("选中",   "指挥官点选该单位时的应答语音（变体）。"),
    "sel":  ("选中",   "点选时播放的确认音。"),
    "sela": ("选中",   "点选时播放的确认音（变体）。"),
    "selb": ("选中",   "点选时播放的确认音（变体）。"),
    "selc": ("选中",   "点选时播放的确认音（变体）。"),
    "die":  ("阵亡",   "该单位 / 建筑被摧毁时发出的音效。"),
    "diea": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效。"),
    "dieb": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "diec": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "died": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "dief": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "diee": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "dieg": ("阵亡",   "该单位 / 建筑被摧毁时发出的音效（变体）。"),
    "dia":  ("语音台词", "该单位与指挥官对话的第 1 句台词。"),
    "dib":  ("语音台词", "该单位与指挥官对话的第 2 句台词。"),
    "dic":  ("语音台词", "该单位与指挥官对话的第 3 句台词。"),
    "did":  ("语音台词", "该单位与指挥官对话的后续台词。"),
    "fe":   ("受击",   "单位被敌方火力命中时发出的音效。"),
    "fed":  ("受击",   "单位被敌方火力命中时发出的音效。"),
    "fea":  ("受击",   "单位被敌方火力命中时发出的语音（变体）。"),
    "feb":  ("受击",   "单位被敌方火力命中时发出的语音（变体）。"),
    "fec":  ("受击",   "单位被敌方火力命中时发出的语音（变体）。"),
    "fee":  ("受击",   "单位被敌方火力命中时发出的语音（变体）。"),
    "fef":  ("受击",   "单位被敌方火力命中时发出的语音（变体）。"),
    "ha":   ("语音",   "该单位随机播放的语音台词。"),
    "haa":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "hab":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "hac":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "had":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "hae":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "haa":  ("语音",   "该单位随机播放的语音台词（变体）。"),
    "rea":  ("应答",   "对指挥官指令的应答语音。"),
    "reb":  ("应答",   "对指挥官指令的应答语音（变体）。"),
    "rec":  ("应答",   "对指挥官指令的应答语音（变体）。"),
    "red":  ("应答",   "对指挥官指令的应答语音（变体）。"),
    "ree":  ("应答",   "对指挥官指令的应答语音（变体）。"),
    "exa":  ("语音台词", "随机台词变体 A。"),
    "exb":  ("语音台词", "随机台词变体 B。"),
    "exc":  ("语音台词", "随机台词变体 C。"),
    "lia":  ("嘲讽",   "该单位发动嘲讽 / 嘲笑时的语音。"),
    "lo":   ("循环音", "单位处于待机 / 工作时循环播放的环境音。"),
    "lo1":  ("循环音", "待机循环环境音（变体）。"),
    "lo2":  ("循环音", "待机循环环境音（变体）。"),
    "lo2a": ("循环音", "待机循环环境音（变体）。"),
    "lo2b": ("循环音", "待机循环环境音（变体）。"),
    "lo2c": ("循环音", "待机循环环境音（变体）。"),
    "lo3":  ("循环音", "待机循环环境音（变体）。"),
    "lo4a": ("循环音", "待机循环环境音（变体）。"),
    "lo5a": ("循环音", "待机循环环境音（变体）。"),
    "lo5b": ("循环音", "待机循环环境音（变体）。"),
    "lo6a": ("循环音", "待机循环环境音（变体）。"),
    "loop": ("循环音", "持续循环播放的机械 / 环境音。"),
    "sta":  ("启动",   "动作 / 装置启动时的触发音。"),
    "staa": ("启动",   "动作 / 装置启动时的触发音（变体）。"),
    "stab": ("启动",   "动作 / 装置启动时的触发音（变体）。"),
    "stac": ("启动",   "动作 / 装置启动时的触发音（变体）。"),
    "stad": ("启动",   "动作 / 装置启动时的触发音（变体）。"),
    "cr":   ("建造",   "建筑 / 单位建造完成提示音。"),
    "cria": ("建造",   "建造完成提示音（变体）。"),
    "crib": ("建造",   "建造完成提示音（变体）。"),
    "cric": ("建造",   "建造完成提示音（变体）。"),
    "crid": ("建造",   "建造完成提示音（变体）。"),
    "crif": ("建造",   "建造完成提示音（变体）。"),
    "mog":  ("改装",   "单位升级 / 改装完成时的语音。"),
    "on":   ("开启",   "建筑 / 装置启动、通电时发出的音效。"),
    "of":   ("关闭",   "建筑 / 装置关闭、断电时发出的音效。"),
    "open": ("开启",   "舱门 / 装置开启时发出的音效。"),
    "pow":  ("能量",   "能量武器充能 / 开火时发出的音效。"),
    "up":   ("升起",   "单位 / 装置升起时发出的音效。"),
    "down": ("下降",   "单位 / 装置下降时发出的音效。"),
    "mof":  ("收起",   "收起武器 / 收工时的音效。"),
    "tele": ("传送",   "超时空传送生效时发出的音效。"),
    "read": ("读取",   "系统读取 / 加载时发出的音效。"),
    "laun": ("发射",   "导弹 / 火箭发射时发出的音效。"),
    "expl": ("爆炸",   "爆炸 / 冲击时发出的音效。"),
    "intr": ("过场",   "过场动画 / 战役简报音乐。"),
    "def":  ("防御",   "防御工事激活时发出的音效。"),
    "dom":  ("心灵主宰", "尤里心灵控制生效时发出的音效。"),
    "rev":  ("反转",   "时间反转效果音。"),
    "snuk": ("核弹",   "核弹发射 / 爆炸相关音效。"),
    "act":  ("动作",   "通用动作触发音。"),
    "now":  ("就绪",   "单位就绪 / 待命提示音。"),
    "kill": ("击杀",   "击杀敌方单位时的语音。"),
}

VOICE_RE = re.compile(r'^(\d{1,2})([a-g]?)$')

# --------------------------------------------------------------------------
# 阵营 / 原型 字典
# --------------------------------------------------------------------------
SIDES = {"soviet": "苏军", "allied": "盟军", "yuri": "尤里", "other": "系统 / 环境"}
PROTO_ZH = {
    "infantry": "步兵", "vehicle": "载具", "air": "空军", "naval": "海军",
    "structure": "建筑", "animal": "动物", "nature": "环境",
    "ui": "界面", "support": "支援 / 超级武器", "other": "其他",
}

# --------------------------------------------------------------------------
# 兵种名(unit_zh) -> (side, proto) 直接键控
# --------------------------------------------------------------------------
UNIT_SIDE_PROTO = {
    "动员兵":      ("soviet", "infantry"),
    "防空步兵":    ("soviet", "infantry"),
    "磁暴步兵":    ("soviet", "infantry"),
    "疯狂伊万":    ("soviet", "infantry"),
    "恐怖分子":    ("soviet", "infantry"),
    "辐射工兵":    ("soviet", "infantry"),
    "鲍里斯":      ("soviet", "infantry"),
    "尤里复制人":  ("yuri",   "infantry"),
    "犀牛坦克":    ("soviet", "vehicle"),
    "防空履带车":  ("soviet", "vehicle"),
    "坦克杀手":    ("soviet", "vehicle"),
    "自爆卡车":    ("soviet", "vehicle"),
    "V3火箭发射车":("soviet", "vehicle"),
    "无畏级战舰":  ("soviet", "naval"),
    "台风潜艇":    ("soviet", "naval"),
    "基洛夫空艇":  ("soviet", "air"),
    "米格战机":    ("soviet", "air"),
    "恐怖机器人":  ("soviet", "vehicle"),
    "武装矿车":    ("soviet", "vehicle"),
    "机器人坦克":  ("soviet", "vehicle"),
    "磁能坦克":    ("soviet", "vehicle"),
    "悬浮单位":    ("other",  "vehicle"),
    "驻军":        ("soviet", "other"),
    "天启坦克":    ("soviet", "vehicle"),
    "战车工厂":    ("soviet", "structure"),
    "测试设施":    ("soviet", "structure"),
    "核子反应堆":  ("soviet", "structure"),
    "特斯拉线圈":  ("soviet", "structure"),
    "心灵感应器":  ("soviet", "structure"),
    "工业工厂":    ("soviet", "structure"),
    "哨戒炮":      ("soviet", "structure"),
    "爱国者导弹":  ("soviet", "structure"),
    "防空炮":      ("soviet", "structure"),
    "克隆缸":      ("soviet", "structure"),
    "生化反应堆":  ("soviet", "structure"),
    "金属存储库":  ("soviet", "structure"),
    "炼油厂":      ("soviet", "structure"),
    "矿石精炼厂":  ("soviet", "structure"),
    "坦克陈列室":  ("soviet", "structure"),
    "装甲兵营":    ("soviet", "structure"),
    "苏军基地":    ("soviet", "structure"),
    "苏军建筑":    ("soviet", "structure"),
    "美国大兵":    ("allied", "infantry"),
    "间谍":        ("allied", "infantry"),
    "谭雅":        ("allied", "infantry"),
    "工程师":      ("allied", "infantry"),
    "超时空军团兵":("allied", "infantry"),
    "激光步兵":    ("allied", "infantry"),
    "火箭兵":      ("allied", "infantry"),
    "狙击手":      ("allied", "infantry"),
    "伪装兵":      ("allied", "infantry"),
    "初始兵种":    ("allied", "infantry"),
    "机密单位":    ("allied", "infantry"),
    "滑行兵":      ("allied", "infantry"),
    "军犬":        ("allied", "infantry"),
    "灰熊坦克":    ("allied", "vehicle"),
    "光棱坦克":    ("allied", "vehicle"),
    "步兵战车":    ("allied", "vehicle"),
    "鱼鹰运输机":  ("allied", "air"),
    "光棱塔":      ("allied", "structure"),
    "盖特机炮":    ("allied", "structure"),
    "裂缝产生器":  ("allied", "structure"),
    "缆车":        ("allied", "other"),
    "海豚":        ("allied", "naval"),
    "粒子炮":      ("allied", "support"),
    "华盛顿纪念碑":("allied", "structure"),
    "战斗碉堡":    ("allied", "structure"),
    "夜鹰直升机":  ("allied", "air"),
    "黑鹰战机":    ("allied", "air"),
    "驱逐舰":      ("allied", "naval"),
    "兵营":        ("allied", "structure"),
    "发电厂":      ("allied", "structure"),
    "间谍卫星":    ("allied", "ui"),
    "海豹突击队":  ("allied", "infantry"),
    "磁能步兵":    ("allied", "infantry"),
    "爱因斯坦":    ("allied", "infantry"),
    "病毒狙击手":  ("yuri",   "infantry"),
    "狂兽人":      ("yuri",   "infantry"),
    "尤里":        ("yuri",   "infantry"),
    "尤里基地":    ("yuri",   "structure"),
    "研磨厂":      ("yuri",   "structure"),
    "盖特坦克":    ("yuri",   "vehicle"),
    "磁电坦克":    ("yuri",   "vehicle"),
    "心灵控制车":  ("yuri",   "vehicle"),
    "坦克":        ("allied", "vehicle"),
    "炮塔":        ("other",  "structure"),
    "雷达":        ("other",  "ui"),
    "建筑受损":    ("other",  "structure"),
    "火力":        ("other",  "other"),
    "无线电":      ("other",  "ui"),
    "爆炸":        ("other",  "other"),
    "电力":        ("other",  "ui"),
    "空袭警报":    ("other",  "ui"),
    "显示器":      ("other",  "ui"),
    "矿石":        ("other",  "other"),
    "矿石上升":    ("other",  "other"),
    "心灵放大":    ("other",  "other"),
    "船":          ("other",  "naval"),
    "车":          ("other",  "vehicle"),
    "灯塔":        ("other",  "structure"),
    "大本钟":      ("other",  "structure"),
    "黑巡航舰":    ("other",  "naval"),
    "牛":          ("other",  "animal"),
    "起重机":      ("other",  "other"),
    "相机":        ("other",  "other"),
    "编钟":        ("other",  "other"),
    "铜管":        ("other",  "other"),
    "拆除":        ("other",  "ui"),
    "进入":        ("other",  "ui"),
    "离开":        ("other",  "ui"),
    "拖船":        ("other",  "naval"),
    "升级":        ("other",  "ui"),
    "计时震撼":    ("other",  "ui"),
    "维里迪安":    ("other",  "nature"),
    "信标":        ("other",  "ui"),
    "导航信标":    ("other",  "ui"),
    "导航":        ("other",  "ui"),
    "奖励":        ("other",  "ui"),
    "指令":        ("other",  "ui"),
    "放置":        ("other",  "ui"),
    "文本":        ("other",  "ui"),
    "新游戏":      ("other",  "ui"),
    "消息":        ("other",  "ui"),
    "滑动":        ("other",  "ui"),
    "滚动":        ("other",  "ui"),
    "菜单滚动":    ("other",  "ui"),
    "菜单点击":    ("other",  "ui"),
    "欢呼":        ("other",  "ui"),
    "警告":        ("other",  "ui"),
    "计划":        ("other",  "ui"),
    "计划添加":    ("other",  "ui"),
    "队列":        ("other",  "ui"),
    "维修":        ("other",  "ui"),
    "选择建造":    ("other",  "ui"),
    "金额":        ("other",  "ui"),
    "账本":        ("other",  "ui"),
    "标签":        ("other",  "ui"),
    "游戏关闭":    ("other",  "ui"),
    "移动循环":    ("other",  "ui"),
    "资料片音效":  ("other",  "other"),
    "内部/室内":    ("other",  "other"),
    "将军":        ("other",  "other"),
    "小队":        ("other",  "other"),
    "装甲兵":      ("other",  "other"),
    "发射井":      ("other",  "structure"),
    "闪光弹":      ("other",  "other"),
    "鸟鸣":        ("other",  "animal"),
    "蟋蟀":        ("other",  "animal"),
    "猫头鹰":      ("other",  "animal"),
    "海鸥":        ("other",  "animal"),
    "海浪":        ("other",  "nature"),
    "风":          ("other",  "nature"),
    "沙漠":        ("other",  "nature"),
    "丛林":        ("other",  "nature"),
    "城市":        ("other",  "nature"),
    "河流":        ("other",  "nature"),
    "树":          ("other",  "nature"),
    "推土机":      ("other",  "other"),
    "水塔":        ("other",  "structure"),
    "核弹发射井":  ("other",  "support"),
    "铁幕":        ("other",  "support"),
    "心灵控制器":  ("other",  "support"),
    "天气控制机":  ("other",  "support"),
    "解放军":      ("other",  "support"),
    "力场护盾":    ("other",  "support"),
    "基因突变器":  ("other",  "support"),
    "超时空传送仪":("other",  "support"),
    "时间机器":    ("other",  "support"),
    "心灵控制":    ("other",  "support"),
    "解放军·甲":   ("other",  "support"),
    "解放军·乙":   ("other",  "support"),
    "侦察车":      ("other",  "vehicle"),
}

# 通用 fallback：前缀 -> 阵营/原型的保守启发
PREFIX_HINT = {
    "i": ("soviet", "infantry"),
    "v": ("allied", "vehicle"),
    "b": ("soviet", "structure"),
    "s": ("other",  "support"),
    "g": ("other",  "structure"),
    "a": ("other",  "nature"),
    "u": ("other",  "ui"),
    "x": ("other",  "other"),
}

# --------------------------------------------------------------------------
# 从文件名稳健还原基础代码
# --------------------------------------------------------------------------
_STRIP = sorted(
    [k for k in ACTION_INFO if len(k) >= 2],
    key=len, reverse=True
)
_STRIP_RE = re.compile(r"(" + "|".join(re.escape(s) for s in _STRIP) + r")$")
_RESIDUAL = [
    "depa", "de", "see", "seg", "cra", "atta", "ati", "pa", "dna", "upa",
    "repa", "tran", "snap", "bo", "lo", "crb", "cre", "crc", "sna", "fea", "fef",
    "shaa", "haa", "hub", "rub", "go", "ba", "bb", "bc", "aa", "ab",
    "1", "2", "3", "4", "a", "e", "i",
]
_RESIDUAL_RE = re.compile(r"(" + "|".join(re.escape(s) for s in _RESIDUAL) + r")$")
_VOICE_RE = re.compile(r"(\d{1,2}[a-g]?)$")


def safe_base(name: str) -> str:
    """剥离语音序号与动作后缀，还原基础代码。"""
    n = name
    m = _VOICE_RE.search(n)
    if m and len(n) - len(m.group(1)) >= 2:
        n = n[:m.start()]
    if n.lower() in CODE_DICT:
        return n
    changed = True
    while changed:
        changed = False
        new = _STRIP_RE.sub("", n)
        if new != n and len(new) >= 2:
            if new.lower() in CODE_DICT:
                return new
            n = new
            changed = True
    cand = _RESIDUAL_RE.sub("", n)
    if cand != n and len(cand) >= 2 and cand.lower() in CODE_DICT:
        return cand
    return n


def resolve_item(it: dict) -> dict:
    """给一条 sound 条目补充 side / side_zh / proto / proto_zh / status_zh / status_desc。"""
    name = it.get("name") or it.get("file", "")
    base = safe_base(name).lower()
    zh = it.get("unit_zh") or base

    side = proto = None
    code = None
    if zh in UNIT_SIDE_PROTO:
        side, proto = UNIT_SIDE_PROTO[zh]
    else:
        for c in sorted(CODE_DICT, key=len, reverse=True):
            if base == c or base.startswith(c):
                code = c
                break
        if code:
            side, proto = CODE_DICT[code][2], CODE_DICT[code][3]
        else:
            side, proto = PREFIX_HINT.get(base[:1], ("other", "other"))

    action = it.get("action", "") or ""
    if action in ACTION_INFO:
        status_zh, status_desc = ACTION_INFO[action]
    else:
        vm = VOICE_RE.match(action)
        if vm:
            n = int(vm.group(1))
            letter = vm.group(2)
            status_zh = "语音台词"
            status_desc = f"该单位 / 系统的第 {n} 句语音台词" + (f"（{letter} 版）" if letter else "") + "。"
        else:
            status_zh = it.get("action_zh") or "音效"
            status_desc = "该单位 / 系统触发的音效。"

    return {
        "side": side,
        "side_zh": SIDES.get(side, "其他"),
        "proto": proto,
        "proto_zh": PROTO_ZH.get(proto, "其他"),
        "status_zh": status_zh,
        "status_desc": status_desc,
        "code": code or base,
    }